version: "2"

linters:
  default: none
  enable:
    # golangci-lint defaults:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Non-default linters:
    - copyloopvar # prefer Go 1.22 loop semantics
    - errname     # standardized error naming
    - errorlint   # Go 1.13 error wrapping
    - gocritic    # general issues
    - intrange    # prefer "range N" over "x := 0; x < N; x++".
    - loggercheck # key-value pairs for structured logs
    - makezero    # catch make([]T, N) used with append
    - musttag     # serialized structs must be tagged
    - nolintlint  # nolint rules
    - perfsprint  # fmt.Sprintf alternatives
    - revive      # style
    - unconvert   # unnecessary type conversions
    - usetesting  # prefer t.TempDir, t.Chdir, etc.

  settings:

    errcheck:
      exclude-functions:
        # Usually used in the same capacity as fmt.Print*.
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln

        # This is always a strings.Builder, and can't fail.
        - (go.abhg.dev/gs/internal/ui.Writer).WriteString
        - (go.abhg.dev/gs/internal/ui.Writer).Write

    govet:
      enable:
        - nilness
        - reflectvaluecompare
        - sortslice
        - unusedwrite

    loggercheck:
      rules:
        - (*go.abhg.dev/gs/internal/log.Logger).Trace
        - (*go.abhg.dev/gs/internal/log.Logger).Debug
        - (*go.abhg.dev/gs/internal/log.Logger).Info
        - (*go.abhg.dev/gs/internal/log.Logger).Warn
        - (*go.abhg.dev/gs/internal/log.Logger).Error
        - (*go.abhg.dev/gs/internal/log.Logger).Fatal
        - (*go.abhg.dev/gs/internal/log.Logger).Log
        - (*go.abhg.dev/gs/internal/log.Logger).With

  exclusions:
    generated: lax
    rules:

      # staticcheck already has smarter checks for empty blocks.
      # revive's empty-block linter has false positives.
      # For example, as of writing this, the following is not allowed.
      #   for foo() { }
      - linters: [revive]
        text: 'empty-block: this block is empty, you can remove it'

      - linters: [musttag]
        path: _test.go$

formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax

issues:
  # Print all issues reported by all linters.
  max-issues-per-linter: 0
  max-same-issues: 0
