version: 2
project_name: git-spice

builds:
  - env:
      - CGO_ENABLED=0
    main: .
    binary: gs
    goos: [darwin, linux, windows]
    goarch: [amd64, arm64, arm]
    goarm: [5, 6, 7]
    ldflags: '-s -w -X main._version={{.Version}}'
    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm
    flags:
      - -trimpath

archives:
  - formats: tar.gz
    # uname compatible archive name.
    name_template: >-
      {{- .ProjectName }}.
      {{- title .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if (and (eq .Arch "arm64") (eq .Os "linux")) }}aarch64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

release:
  prerelease: auto

aurs:
  - name: git-spice-bin
    homepage: "https://abhinav.github.io/git-spice/"
    description: "A tool for stacking Git branches."
    maintainers:
      - 'Abhinav Gupta <mail@abhinavg.net>'
    license: "GPL-3.0-or-later"
    git_url: "ssh://aur@aur.archlinux.org/git-spice-bin.git"
    skip_upload: auto
    private_key: '{{ .Env.AUR_KEY }}'
    conflicts:
      - git-spice    # no non-bin package exists yet, but just in case
      - ghostscript  # ghostscript also provides a 'gs' binary
    package: |-
      install -Dm755 "./gs" "${pkgdir}/usr/bin/gs"
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/git-spice/LICENSE"
      install -Dm644 "./README.md" "${pkgdir}/usr/share/doc/git-spice/README.md"
      install -Dm644 "./CHANGELOG.md" "${pkgdir}/usr/share/doc/git-spice/CHANGELOG.md"
    commit_author:
      name: Abhinav Gupta
      email: mail@abhinavg.net

homebrew_casks:
  - repository:
      owner: abhinav
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_msg_template: "{{ .ProjectName }}: Update formula to {{ .Tag }}"
    commit_author:
      name: Abhinav Gupta
      email: mail@abhinavg.net
    homepage: https://abhinav.github.io/git-spice/
    description: "A tool for stacking Git branches."
    license: "GPL-3.0-or-later"
    skip_upload: auto
    binary: gs
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gs"]
          end


checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incminor .Tag }}-dev"
