// Code generated by MockGen. DO NOT EDIT.
// Source: go.abhg.dev/gs/internal/gateway/bitbucket (interfaces: Gateway)
//
// Generated by this command:
//
//	mockgen -destination=mocks_test.go -package=bitbucket -write_package_comment=false -typed=true go.abhg.dev/gs/internal/gateway/bitbucket Gateway
//

package bitbucket

import (
	context "context"
	iter "iter"
	reflect "reflect"

	forge "go.abhg.dev/gs/internal/forge"
	bitbucket "go.abhg.dev/gs/internal/gateway/bitbucket"
	git "go.abhg.dev/gs/internal/git"
	gomock "go.uber.org/mock/gomock"
)

// MockGateway is a mock of Gateway interface.
type MockGateway struct {
	ctrl     *gomock.Controller
	recorder *MockGatewayMockRecorder
	isgomock struct{}
}

// MockGatewayMockRecorder is the mock recorder for MockGateway.
type MockGatewayMockRecorder struct {
	mock *MockGateway
}

// NewMockGateway creates a new mock instance.
func NewMockGateway(ctrl *gomock.Controller) *MockGateway {
	mock := &MockGateway{ctrl: ctrl}
	mock.recorder = &MockGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGateway) EXPECT() *MockGatewayMockRecorder {
	return m.recorder
}

// ChangeMergeability mocks base method.
func (m *MockGateway) ChangeMergeability(ctx context.Context, number int64) (forge.ChangeMergeability, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeMergeability", ctx, number)
	ret0, _ := ret[0].(forge.ChangeMergeability)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangeMergeability indicates an expected call of ChangeMergeability.
func (mr *MockGatewayMockRecorder) ChangeMergeability(ctx, number any) *MockGatewayChangeMergeabilityCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeMergeability", reflect.TypeOf((*MockGateway)(nil).ChangeMergeability), ctx, number)
	return &MockGatewayChangeMergeabilityCall{Call: call}
}

// MockGatewayChangeMergeabilityCall wrap *gomock.Call
type MockGatewayChangeMergeabilityCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGatewayChangeMergeabilityCall) Return(arg0 forge.ChangeMergeability, arg1 error) *MockGatewayChangeMergeabilityCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGatewayChangeMergeabilityCall) Do(f func(context.Context, int64) (forge.ChangeMergeability, error)) *MockGatewayChangeMergeabilityCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGatewayChangeMergeabilityCall) DoAndReturn(f func(context.Context, int64) (forge.ChangeMergeability, error)) *MockGatewayChangeMergeabilityCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ChangeTemplate mocks base method.
func (m *MockGateway) ChangeTemplate(ctx context.Context, path string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeTemplate", ctx, path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangeTemplate indicates an expected call of ChangeTemplate.
func (mr *MockGatewayMockRecorder) ChangeTemplate(ctx, path any) *MockGatewayChangeTemplateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeTemplate", reflect.TypeOf((*MockGateway)(nil).ChangeTemplate), ctx, path)
	return &MockGatewayChangeTemplateCall{Call: call}
}

// MockGatewayChangeTemplateCall wrap *gomock.Call
type MockGatewayChangeTemplateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGatewayChangeTemplateCall) Return(arg0 string, arg1 error) *MockGatewayChangeTemplateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGatewayChangeTemplateCall) Do(f func(context.Context, string) (string, error)) *MockGatewayChangeTemplateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGatewayChangeTemplateCall) DoAndReturn(f func(context.Context, string) (string, error)) *MockGatewayChangeTemplateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ChangeURL mocks base method.
func (m *MockGateway) ChangeURL(number int64) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeURL", number)
	ret0, _ := ret[0].(string)
	return ret0
}

// ChangeURL indicates an expected call of ChangeURL.
func (mr *MockGatewayMockRecorder) ChangeURL(number any) *MockGatewayChangeURLCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeURL", reflect.TypeOf((*MockGateway)(nil).ChangeURL), number)
	return &MockGatewayChangeURLCall{Call: call}
}

// MockGatewayChangeURLCall wrap *gomock.Call
type MockGatewayChangeURLCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGatewayChangeURLCall) Return(arg0 string) *MockGatewayChangeURLCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGatewayChangeURLCall) Do(f func(int64) string) *MockGatewayChangeURLCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGatewayChangeURLCall) DoAndReturn(f func(int64) string) *MockGatewayChangeURLCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateChange mocks base method.
func (m *MockGateway) CreateChange(ctx context.Context, req bitbucket.CreateChangeRequest) (*bitbucket.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChange", ctx, req)
	ret0, _ := ret[0].(*bitbucket.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChange indicates an expected call of CreateChange.
func (mr *MockGatewayMockRecorder) CreateChange(ctx, req any) *MockGatewayCreateChangeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChange", reflect.TypeOf((*MockGateway)(nil).CreateChange), ctx, req)
	return &MockGatewayCreateChangeCall{Call: call}
}

// MockGatewayCreateChangeCall wrap *gomock.Call
type MockGatewayCreateChangeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGatewayCreateChangeCall) Return(arg0 *bitbucket.PullRequest, arg1 error) *MockGatewayCreateChangeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGatewayCreateChangeCall) Do(f func(context.Context, bitbucket.CreateChangeRequest) (*bitbucket.PullRequest, error)) *MockGatewayCreateChangeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGatewayCreateChangeCall) DoAndReturn(f func(context.Context, bitbucket.CreateChangeRequest) (*bitbucket.PullRequest, error)) *MockGatewayCreateChangeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateComment mocks base method.
func (m *MockGateway) CreateComment(ctx context.Context, prID int64, body string) (*bitbucket.ChangeComment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateComment", ctx, prID, body)
	ret0, _ := ret[0].(*bitbucket.ChangeComment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateComment indicates an expected call of CreateComment.
func (mr *MockGatewayMockRecorder) CreateComment(ctx, prID, body any) *MockGatewayCreateCommentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComment", reflect.TypeOf((*MockGateway)(nil).CreateComment), ctx, prID, body)
	return &MockGatewayCreateCommentCall{Call: call}
}

// MockGatewayCreateCommentCall wrap *gomock.Call
type MockGatewayCreateCommentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGatewayCreateCommentCall) Return(arg0 *bitbucket.ChangeComment, arg1 error) *MockGatewayCreateCommentCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGatewayCreateCommentCall) Do(f func(context.Context, int64, string) (*bitbucket.ChangeComment, error)) *MockGatewayCreateCommentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGatewayCreateCommentCall) DoAndReturn(f func(context.Context, int64, string) (*bitbucket.ChangeComment, error)) *MockGatewayCreateCommentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteComment mocks base method.
func (m *MockGateway) DeleteComment(ctx context.Context, c *bitbucket.ChangeComment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteComment", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteComment indicates an expected call of DeleteComment.
func (mr *MockGatewayMockRecorder) DeleteComment(ctx, c any) *MockGatewayDeleteCommentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteComment", reflect.TypeOf((*MockGateway)(nil).DeleteComment), ctx, c)
	return &MockGatewayDeleteCommentCall{Call: call}
}

// MockGatewayDeleteCommentCall wrap *gomock.Call
type MockGatewayDeleteCommentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c_2 *MockGatewayDeleteCommentCall) Return(arg0 error) *MockGatewayDeleteCommentCall {
	c_2.Call = c_2.Call.Return(arg0)
	return c_2
}

// Do rewrite *gomock.Call.Do
func (c_2 *MockGatewayDeleteCommentCall) Do(f func(context.Context, *bitbucket.ChangeComment) error) *MockGatewayDeleteCommentCall {
	c_2.Call = c_2.Call.Do(f)
	return c_2
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c_2 *MockGatewayDeleteCommentCall) DoAndReturn(f func(context.Context, *bitbucket.ChangeComment) error) *MockGatewayDeleteCommentCall {
	c_2.Call = c_2.Call.DoAndReturn(f)
	return c_2
}

// FindChangesByBranch mocks base method.
func (m *MockGateway) FindChangesByBranch(ctx context.Context, branch string, opts bitbucket.FindChangesOptions) ([]*bitbucket.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindChangesByBranch", ctx, branch, opts)
	ret0, _ := ret[0].([]*bitbucket.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindChangesByBranch indicates an expected call of FindChangesByBranch.
func (mr *MockGatewayMockRecorder) FindChangesByBranch(ctx, branch, opts any) *MockGatewayFindChangesByBranchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindChangesByBranch", reflect.TypeOf((*MockGateway)(nil).FindChangesByBranch), ctx, branch, opts)
	return &MockGatewayFindChangesByBranchCall{Call: call}
}

// MockGatewayFindChangesByBranchCall wrap *gomock.Call
type MockGatewayFindChangesByBranchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGatewayFindChangesByBranchCall) Return(arg0 []*bitbucket.PullRequest, arg1 error) *MockGatewayFindChangesByBranchCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGatewayFindChangesByBranchCall) Do(f func(context.Context, string, bitbucket.FindChangesOptions) ([]*bitbucket.PullRequest, error)) *MockGatewayFindChangesByBranchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGatewayFindChangesByBranchCall) DoAndReturn(f func(context.Context, string, bitbucket.FindChangesOptions) ([]*bitbucket.PullRequest, error)) *MockGatewayFindChangesByBranchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetChange mocks base method.
func (m *MockGateway) GetChange(ctx context.Context, number int64) (*bitbucket.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChange", ctx, number)
	ret0, _ := ret[0].(*bitbucket.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChange indicates an expected call of GetChange.
func (mr *MockGatewayMockRecorder) GetChange(ctx, number any) *MockGatewayGetChangeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChange", reflect.TypeOf((*MockGateway)(nil).GetChange), ctx, number)
	return &MockGatewayGetChangeCall{Call: call}
}

// MockGatewayGetChangeCall wrap *gomock.Call
type MockGatewayGetChangeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGatewayGetChangeCall) Return(arg0 *bitbucket.PullRequest, arg1 error) *MockGatewayGetChangeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGatewayGetChangeCall) Do(f func(context.Context, int64) (*bitbucket.PullRequest, error)) *MockGatewayGetChangeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGatewayGetChangeCall) DoAndReturn(f func(context.Context, int64) (*bitbucket.PullRequest, error)) *MockGatewayGetChangeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListComments mocks base method.
func (m *MockGateway) ListComments(ctx context.Context, prID int64, opts bitbucket.ListCommentsOptions) iter.Seq2[*bitbucket.ChangeComment, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListComments", ctx, prID, opts)
	ret0, _ := ret[0].(iter.Seq2[*bitbucket.ChangeComment, error])
	return ret0
}

// ListComments indicates an expected call of ListComments.
func (mr *MockGatewayMockRecorder) ListComments(ctx, prID, opts any) *MockGatewayListCommentsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListComments", reflect.TypeOf((*MockGateway)(nil).ListComments), ctx, prID, opts)
	return &MockGatewayListCommentsCall{Call: call}
}

// MockGatewayListCommentsCall wrap *gomock.Call
type MockGatewayListCommentsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGatewayListCommentsCall) Return(arg0 iter.Seq2[*bitbucket.ChangeComment, error]) *MockGatewayListCommentsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGatewayListCommentsCall) Do(f func(context.Context, int64, bitbucket.ListCommentsOptions) iter.Seq2[*bitbucket.ChangeComment, error]) *MockGatewayListCommentsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGatewayListCommentsCall) DoAndReturn(f func(context.Context, int64, bitbucket.ListCommentsOptions) iter.Seq2[*bitbucket.ChangeComment, error]) *MockGatewayListCommentsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListCommitChecks mocks base method.
func (m *MockGateway) ListCommitChecks(ctx context.Context, commit git.Hash) ([]forge.ChangeCheck, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCommitChecks", ctx, commit)
	ret0, _ := ret[0].([]forge.ChangeCheck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCommitChecks indicates an expected call of ListCommitChecks.
func (mr *MockGatewayMockRecorder) ListCommitChecks(ctx, commit any) *MockGatewayListCommitChecksCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCommitChecks", reflect.TypeOf((*MockGateway)(nil).ListCommitChecks), ctx, commit)
	return &MockGatewayListCommitChecksCall{Call: call}
}

// MockGatewayListCommitChecksCall wrap *gomock.Call
type MockGatewayListCommitChecksCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGatewayListCommitChecksCall) Return(arg0 []forge.ChangeCheck, arg1 error) *MockGatewayListCommitChecksCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGatewayListCommitChecksCall) Do(f func(context.Context, git.Hash) ([]forge.ChangeCheck, error)) *MockGatewayListCommitChecksCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGatewayListCommitChecksCall) DoAndReturn(f func(context.Context, git.Hash) ([]forge.ChangeCheck, error)) *MockGatewayListCommitChecksCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MergeChange mocks base method.
func (m *MockGateway) MergeChange(ctx context.Context, number int64, method forge.MergeMethod) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergeChange", ctx, number, method)
	ret0, _ := ret[0].(error)
	return ret0
}

// MergeChange indicates an expected call of MergeChange.
func (mr *MockGatewayMockRecorder) MergeChange(ctx, number, method any) *MockGatewayMergeChangeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergeChange", reflect.TypeOf((*MockGateway)(nil).MergeChange), ctx, number, method)
	return &MockGatewayMergeChangeCall{Call: call}
}

// MockGatewayMergeChangeCall wrap *gomock.Call
type MockGatewayMergeChangeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGatewayMergeChangeCall) Return(arg0 error) *MockGatewayMergeChangeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGatewayMergeChangeCall) Do(f func(context.Context, int64, forge.MergeMethod) error) *MockGatewayMergeChangeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGatewayMergeChangeCall) DoAndReturn(f func(context.Context, int64, forge.MergeMethod) error) *MockGatewayMergeChangeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Product mocks base method.
func (m *MockGateway) Product() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Product")
	ret0, _ := ret[0].(string)
	return ret0
}

// Product indicates an expected call of Product.
func (mr *MockGatewayMockRecorder) Product() *MockGatewayProductCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Product", reflect.TypeOf((*MockGateway)(nil).Product))
	return &MockGatewayProductCall{Call: call}
}

// MockGatewayProductCall wrap *gomock.Call
type MockGatewayProductCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGatewayProductCall) Return(arg0 string) *MockGatewayProductCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGatewayProductCall) Do(f func() string) *MockGatewayProductCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGatewayProductCall) DoAndReturn(f func() string) *MockGatewayProductCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ResolvableComments mocks base method.
func (m *MockGateway) ResolvableComments(ctx context.Context, prID int64) iter.Seq2[*bitbucket.ResolvableComment, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolvableComments", ctx, prID)
	ret0, _ := ret[0].(iter.Seq2[*bitbucket.ResolvableComment, error])
	return ret0
}

// ResolvableComments indicates an expected call of ResolvableComments.
func (mr *MockGatewayMockRecorder) ResolvableComments(ctx, prID any) *MockGatewayResolvableCommentsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolvableComments", reflect.TypeOf((*MockGateway)(nil).ResolvableComments), ctx, prID)
	return &MockGatewayResolvableCommentsCall{Call: call}
}

// MockGatewayResolvableCommentsCall wrap *gomock.Call
type MockGatewayResolvableCommentsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGatewayResolvableCommentsCall) Return(arg0 iter.Seq2[*bitbucket.ResolvableComment, error]) *MockGatewayResolvableCommentsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGatewayResolvableCommentsCall) Do(f func(context.Context, int64) iter.Seq2[*bitbucket.ResolvableComment, error]) *MockGatewayResolvableCommentsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGatewayResolvableCommentsCall) DoAndReturn(f func(context.Context, int64) iter.Seq2[*bitbucket.ResolvableComment, error]) *MockGatewayResolvableCommentsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetChangeDraft mocks base method.
func (m *MockGateway) SetChangeDraft(ctx context.Context, number int64, draft bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetChangeDraft", ctx, number, draft)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetChangeDraft indicates an expected call of SetChangeDraft.
func (mr *MockGatewayMockRecorder) SetChangeDraft(ctx, number, draft any) *MockGatewaySetChangeDraftCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetChangeDraft", reflect.TypeOf((*MockGateway)(nil).SetChangeDraft), ctx, number, draft)
	return &MockGatewaySetChangeDraftCall{Call: call}
}

// MockGatewaySetChangeDraftCall wrap *gomock.Call
type MockGatewaySetChangeDraftCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGatewaySetChangeDraftCall) Return(arg0 error) *MockGatewaySetChangeDraftCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGatewaySetChangeDraftCall) Do(f func(context.Context, int64, bool) error) *MockGatewaySetChangeDraftCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGatewaySetChangeDraftCall) DoAndReturn(f func(context.Context, int64, bool) error) *MockGatewaySetChangeDraftCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateChange mocks base method.
func (m *MockGateway) UpdateChange(ctx context.Context, number int64, update bitbucket.ChangeUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateChange", ctx, number, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateChange indicates an expected call of UpdateChange.
func (mr *MockGatewayMockRecorder) UpdateChange(ctx, number, update any) *MockGatewayUpdateChangeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateChange", reflect.TypeOf((*MockGateway)(nil).UpdateChange), ctx, number, update)
	return &MockGatewayUpdateChangeCall{Call: call}
}

// MockGatewayUpdateChangeCall wrap *gomock.Call
type MockGatewayUpdateChangeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGatewayUpdateChangeCall) Return(arg0 error) *MockGatewayUpdateChangeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGatewayUpdateChangeCall) Do(f func(context.Context, int64, bitbucket.ChangeUpdate) error) *MockGatewayUpdateChangeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGatewayUpdateChangeCall) DoAndReturn(f func(context.Context, int64, bitbucket.ChangeUpdate) error) *MockGatewayUpdateChangeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateComment mocks base method.
func (m *MockGateway) UpdateComment(ctx context.Context, c *bitbucket.ChangeComment, body string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateComment", ctx, c, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateComment indicates an expected call of UpdateComment.
func (mr *MockGatewayMockRecorder) UpdateComment(ctx, c, body any) *MockGatewayUpdateCommentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateComment", reflect.TypeOf((*MockGateway)(nil).UpdateComment), ctx, c, body)
	return &MockGatewayUpdateCommentCall{Call: call}
}

// MockGatewayUpdateCommentCall wrap *gomock.Call
type MockGatewayUpdateCommentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c_2 *MockGatewayUpdateCommentCall) Return(arg0 error) *MockGatewayUpdateCommentCall {
	c_2.Call = c_2.Call.Return(arg0)
	return c_2
}

// Do rewrite *gomock.Call.Do
func (c_2 *MockGatewayUpdateCommentCall) Do(f func(context.Context, *bitbucket.ChangeComment, string) error) *MockGatewayUpdateCommentCall {
	c_2.Call = c_2.Call.Do(f)
	return c_2
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c_2 *MockGatewayUpdateCommentCall) DoAndReturn(f func(context.Context, *bitbucket.ChangeComment, string) error) *MockGatewayUpdateCommentCall {
	c_2.Call = c_2.Call.DoAndReturn(f)
	return c_2
}
