// Code generated by MockGen. DO NOT EDIT.
// Source: go.abhg.dev/gs/internal/forge (interfaces: Forge,RepositoryID,Repository,WithInlineComments)
//
// Generated by this command:
//
//	mockgen -destination=forgetest/mocks.go -package forgetest -typed -write_package_comment=false . Forge,RepositoryID,Repository,WithInlineComments
//

package forgetest

import (
	context "context"
	json "encoding/json"
	iter "iter"
	reflect "reflect"

	forge "go.abhg.dev/gs/internal/forge"
	secret "go.abhg.dev/gs/internal/secret"
	ui "go.abhg.dev/gs/internal/ui"
	gomock "go.uber.org/mock/gomock"
)

// MockForge is a mock of Forge interface.
type MockForge struct {
	ctrl     *gomock.Controller
	recorder *MockForgeMockRecorder
	isgomock struct{}
}

// MockForgeMockRecorder is the mock recorder for MockForge.
type MockForgeMockRecorder struct {
	mock *MockForge
}

// NewMockForge creates a new mock instance.
func NewMockForge(ctrl *gomock.Controller) *MockForge {
	mock := &MockForge{ctrl: ctrl}
	mock.recorder = &MockForgeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForge) EXPECT() *MockForgeMockRecorder {
	return m.recorder
}

// AuthenticationFlow mocks base method.
func (m *MockForge) AuthenticationFlow(ctx context.Context, view ui.View) (forge.AuthenticationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthenticationFlow", ctx, view)
	ret0, _ := ret[0].(forge.AuthenticationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthenticationFlow indicates an expected call of AuthenticationFlow.
func (mr *MockForgeMockRecorder) AuthenticationFlow(ctx, view any) *MockForgeAuthenticationFlowCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthenticationFlow", reflect.TypeOf((*MockForge)(nil).AuthenticationFlow), ctx, view)
	return &MockForgeAuthenticationFlowCall{Call: call}
}

// MockForgeAuthenticationFlowCall wrap *gomock.Call
type MockForgeAuthenticationFlowCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockForgeAuthenticationFlowCall) Return(arg0 forge.AuthenticationToken, arg1 error) *MockForgeAuthenticationFlowCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockForgeAuthenticationFlowCall) Do(f func(context.Context, ui.View) (forge.AuthenticationToken, error)) *MockForgeAuthenticationFlowCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockForgeAuthenticationFlowCall) DoAndReturn(f func(context.Context, ui.View) (forge.AuthenticationToken, error)) *MockForgeAuthenticationFlowCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// BaseURL mocks base method.
func (m *MockForge) BaseURL() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BaseURL")
	ret0, _ := ret[0].(string)
	return ret0
}

// BaseURL indicates an expected call of BaseURL.
func (mr *MockForgeMockRecorder) BaseURL() *MockForgeBaseURLCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BaseURL", reflect.TypeOf((*MockForge)(nil).BaseURL))
	return &MockForgeBaseURLCall{Call: call}
}

// MockForgeBaseURLCall wrap *gomock.Call
type MockForgeBaseURLCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockForgeBaseURLCall) Return(arg0 string) *MockForgeBaseURLCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockForgeBaseURLCall) Do(f func() string) *MockForgeBaseURLCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockForgeBaseURLCall) DoAndReturn(f func() string) *MockForgeBaseURLCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CLIPlugin mocks base method.
func (m *MockForge) CLIPlugin() any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CLIPlugin")
	ret0, _ := ret[0].(any)
	return ret0
}

// CLIPlugin indicates an expected call of CLIPlugin.
func (mr *MockForgeMockRecorder) CLIPlugin() *MockForgeCLIPluginCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CLIPlugin", reflect.TypeOf((*MockForge)(nil).CLIPlugin))
	return &MockForgeCLIPluginCall{Call: call}
}

// MockForgeCLIPluginCall wrap *gomock.Call
type MockForgeCLIPluginCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockForgeCLIPluginCall) Return(arg0 any) *MockForgeCLIPluginCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockForgeCLIPluginCall) Do(f func() any) *MockForgeCLIPluginCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockForgeCLIPluginCall) DoAndReturn(f func() any) *MockForgeCLIPluginCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ChangeTemplatePaths mocks base method.
func (m *MockForge) ChangeTemplatePaths() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeTemplatePaths")
	ret0, _ := ret[0].([]string)
	return ret0
}

// ChangeTemplatePaths indicates an expected call of ChangeTemplatePaths.
func (mr *MockForgeMockRecorder) ChangeTemplatePaths() *MockForgeChangeTemplatePathsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeTemplatePaths", reflect.TypeOf((*MockForge)(nil).ChangeTemplatePaths))
	return &MockForgeChangeTemplatePathsCall{Call: call}
}

// MockForgeChangeTemplatePathsCall wrap *gomock.Call
type MockForgeChangeTemplatePathsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockForgeChangeTemplatePathsCall) Return(arg0 []string) *MockForgeChangeTemplatePathsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockForgeChangeTemplatePathsCall) Do(f func() []string) *MockForgeChangeTemplatePathsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockForgeChangeTemplatePathsCall) DoAndReturn(f func() []string) *MockForgeChangeTemplatePathsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ClearAuthenticationToken mocks base method.
func (m *MockForge) ClearAuthenticationToken(arg0 secret.Stash) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearAuthenticationToken", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearAuthenticationToken indicates an expected call of ClearAuthenticationToken.
func (mr *MockForgeMockRecorder) ClearAuthenticationToken(arg0 any) *MockForgeClearAuthenticationTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearAuthenticationToken", reflect.TypeOf((*MockForge)(nil).ClearAuthenticationToken), arg0)
	return &MockForgeClearAuthenticationTokenCall{Call: call}
}

// MockForgeClearAuthenticationTokenCall wrap *gomock.Call
type MockForgeClearAuthenticationTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockForgeClearAuthenticationTokenCall) Return(arg0 error) *MockForgeClearAuthenticationTokenCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockForgeClearAuthenticationTokenCall) Do(f func(secret.Stash) error) *MockForgeClearAuthenticationTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockForgeClearAuthenticationTokenCall) DoAndReturn(f func(secret.Stash) error) *MockForgeClearAuthenticationTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ID mocks base method.
func (m *MockForge) ID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockForgeMockRecorder) ID() *MockForgeIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockForge)(nil).ID))
	return &MockForgeIDCall{Call: call}
}

// MockForgeIDCall wrap *gomock.Call
type MockForgeIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockForgeIDCall) Return(arg0 string) *MockForgeIDCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockForgeIDCall) Do(f func() string) *MockForgeIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockForgeIDCall) DoAndReturn(f func() string) *MockForgeIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LoadAuthenticationToken mocks base method.
func (m *MockForge) LoadAuthenticationToken(arg0 secret.Stash) (forge.AuthenticationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadAuthenticationToken", arg0)
	ret0, _ := ret[0].(forge.AuthenticationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadAuthenticationToken indicates an expected call of LoadAuthenticationToken.
func (mr *MockForgeMockRecorder) LoadAuthenticationToken(arg0 any) *MockForgeLoadAuthenticationTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadAuthenticationToken", reflect.TypeOf((*MockForge)(nil).LoadAuthenticationToken), arg0)
	return &MockForgeLoadAuthenticationTokenCall{Call: call}
}

// MockForgeLoadAuthenticationTokenCall wrap *gomock.Call
type MockForgeLoadAuthenticationTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockForgeLoadAuthenticationTokenCall) Return(arg0 forge.AuthenticationToken, arg1 error) *MockForgeLoadAuthenticationTokenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockForgeLoadAuthenticationTokenCall) Do(f func(secret.Stash) (forge.AuthenticationToken, error)) *MockForgeLoadAuthenticationTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockForgeLoadAuthenticationTokenCall) DoAndReturn(f func(secret.Stash) (forge.AuthenticationToken, error)) *MockForgeLoadAuthenticationTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MarshalChangeID mocks base method.
func (m *MockForge) MarshalChangeID(arg0 forge.ChangeID) (json.RawMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarshalChangeID", arg0)
	ret0, _ := ret[0].(json.RawMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarshalChangeID indicates an expected call of MarshalChangeID.
func (mr *MockForgeMockRecorder) MarshalChangeID(arg0 any) *MockForgeMarshalChangeIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarshalChangeID", reflect.TypeOf((*MockForge)(nil).MarshalChangeID), arg0)
	return &MockForgeMarshalChangeIDCall{Call: call}
}

// MockForgeMarshalChangeIDCall wrap *gomock.Call
type MockForgeMarshalChangeIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockForgeMarshalChangeIDCall) Return(arg0 json.RawMessage, arg1 error) *MockForgeMarshalChangeIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockForgeMarshalChangeIDCall) Do(f func(forge.ChangeID) (json.RawMessage, error)) *MockForgeMarshalChangeIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockForgeMarshalChangeIDCall) DoAndReturn(f func(forge.ChangeID) (json.RawMessage, error)) *MockForgeMarshalChangeIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MarshalChangeMetadata mocks base method.
func (m *MockForge) MarshalChangeMetadata(arg0 forge.ChangeMetadata) (json.RawMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarshalChangeMetadata", arg0)
	ret0, _ := ret[0].(json.RawMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarshalChangeMetadata indicates an expected call of MarshalChangeMetadata.
func (mr *MockForgeMockRecorder) MarshalChangeMetadata(arg0 any) *MockForgeMarshalChangeMetadataCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarshalChangeMetadata", reflect.TypeOf((*MockForge)(nil).MarshalChangeMetadata), arg0)
	return &MockForgeMarshalChangeMetadataCall{Call: call}
}

// MockForgeMarshalChangeMetadataCall wrap *gomock.Call
type MockForgeMarshalChangeMetadataCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockForgeMarshalChangeMetadataCall) Return(arg0 json.RawMessage, arg1 error) *MockForgeMarshalChangeMetadataCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockForgeMarshalChangeMetadataCall) Do(f func(forge.ChangeMetadata) (json.RawMessage, error)) *MockForgeMarshalChangeMetadataCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockForgeMarshalChangeMetadataCall) DoAndReturn(f func(forge.ChangeMetadata) (json.RawMessage, error)) *MockForgeMarshalChangeMetadataCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// OpenRepository mocks base method.
func (m *MockForge) OpenRepository(ctx context.Context, tok forge.AuthenticationToken, repo forge.RepositoryID) (forge.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenRepository", ctx, tok, repo)
	ret0, _ := ret[0].(forge.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenRepository indicates an expected call of OpenRepository.
func (mr *MockForgeMockRecorder) OpenRepository(ctx, tok, repo any) *MockForgeOpenRepositoryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenRepository", reflect.TypeOf((*MockForge)(nil).OpenRepository), ctx, tok, repo)
	return &MockForgeOpenRepositoryCall{Call: call}
}

// MockForgeOpenRepositoryCall wrap *gomock.Call
type MockForgeOpenRepositoryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockForgeOpenRepositoryCall) Return(arg0 forge.Repository, arg1 error) *MockForgeOpenRepositoryCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockForgeOpenRepositoryCall) Do(f func(context.Context, forge.AuthenticationToken, forge.RepositoryID) (forge.Repository, error)) *MockForgeOpenRepositoryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockForgeOpenRepositoryCall) DoAndReturn(f func(context.Context, forge.AuthenticationToken, forge.RepositoryID) (forge.Repository, error)) *MockForgeOpenRepositoryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ParseRepositoryPath mocks base method.
func (m *MockForge) ParseRepositoryPath(arg0 string) (forge.RepositoryID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseRepositoryPath", arg0)
	ret0, _ := ret[0].(forge.RepositoryID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseRepositoryPath indicates an expected call of ParseRepositoryPath.
func (mr *MockForgeMockRecorder) ParseRepositoryPath(arg0 any) *MockForgeParseRepositoryPathCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseRepositoryPath", reflect.TypeOf((*MockForge)(nil).ParseRepositoryPath), arg0)
	return &MockForgeParseRepositoryPathCall{Call: call}
}

// MockForgeParseRepositoryPathCall wrap *gomock.Call
type MockForgeParseRepositoryPathCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockForgeParseRepositoryPathCall) Return(arg0 forge.RepositoryID, arg1 error) *MockForgeParseRepositoryPathCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockForgeParseRepositoryPathCall) Do(f func(string) (forge.RepositoryID, error)) *MockForgeParseRepositoryPathCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockForgeParseRepositoryPathCall) DoAndReturn(f func(string) (forge.RepositoryID, error)) *MockForgeParseRepositoryPathCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SaveAuthenticationToken mocks base method.
func (m *MockForge) SaveAuthenticationToken(arg0 secret.Stash, arg1 forge.AuthenticationToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAuthenticationToken", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveAuthenticationToken indicates an expected call of SaveAuthenticationToken.
func (mr *MockForgeMockRecorder) SaveAuthenticationToken(arg0, arg1 any) *MockForgeSaveAuthenticationTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAuthenticationToken", reflect.TypeOf((*MockForge)(nil).SaveAuthenticationToken), arg0, arg1)
	return &MockForgeSaveAuthenticationTokenCall{Call: call}
}

// MockForgeSaveAuthenticationTokenCall wrap *gomock.Call
type MockForgeSaveAuthenticationTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockForgeSaveAuthenticationTokenCall) Return(arg0 error) *MockForgeSaveAuthenticationTokenCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockForgeSaveAuthenticationTokenCall) Do(f func(secret.Stash, forge.AuthenticationToken) error) *MockForgeSaveAuthenticationTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockForgeSaveAuthenticationTokenCall) DoAndReturn(f func(secret.Stash, forge.AuthenticationToken) error) *MockForgeSaveAuthenticationTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UnmarshalChangeID mocks base method.
func (m *MockForge) UnmarshalChangeID(arg0 json.RawMessage) (forge.ChangeID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarshalChangeID", arg0)
	ret0, _ := ret[0].(forge.ChangeID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnmarshalChangeID indicates an expected call of UnmarshalChangeID.
func (mr *MockForgeMockRecorder) UnmarshalChangeID(arg0 any) *MockForgeUnmarshalChangeIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarshalChangeID", reflect.TypeOf((*MockForge)(nil).UnmarshalChangeID), arg0)
	return &MockForgeUnmarshalChangeIDCall{Call: call}
}

// MockForgeUnmarshalChangeIDCall wrap *gomock.Call
type MockForgeUnmarshalChangeIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockForgeUnmarshalChangeIDCall) Return(arg0 forge.ChangeID, arg1 error) *MockForgeUnmarshalChangeIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockForgeUnmarshalChangeIDCall) Do(f func(json.RawMessage) (forge.ChangeID, error)) *MockForgeUnmarshalChangeIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockForgeUnmarshalChangeIDCall) DoAndReturn(f func(json.RawMessage) (forge.ChangeID, error)) *MockForgeUnmarshalChangeIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UnmarshalChangeMetadata mocks base method.
func (m *MockForge) UnmarshalChangeMetadata(arg0 json.RawMessage) (forge.ChangeMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarshalChangeMetadata", arg0)
	ret0, _ := ret[0].(forge.ChangeMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnmarshalChangeMetadata indicates an expected call of UnmarshalChangeMetadata.
func (mr *MockForgeMockRecorder) UnmarshalChangeMetadata(arg0 any) *MockForgeUnmarshalChangeMetadataCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarshalChangeMetadata", reflect.TypeOf((*MockForge)(nil).UnmarshalChangeMetadata), arg0)
	return &MockForgeUnmarshalChangeMetadataCall{Call: call}
}

// MockForgeUnmarshalChangeMetadataCall wrap *gomock.Call
type MockForgeUnmarshalChangeMetadataCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockForgeUnmarshalChangeMetadataCall) Return(arg0 forge.ChangeMetadata, arg1 error) *MockForgeUnmarshalChangeMetadataCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockForgeUnmarshalChangeMetadataCall) Do(f func(json.RawMessage) (forge.ChangeMetadata, error)) *MockForgeUnmarshalChangeMetadataCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockForgeUnmarshalChangeMetadataCall) DoAndReturn(f func(json.RawMessage) (forge.ChangeMetadata, error)) *MockForgeUnmarshalChangeMetadataCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockRepositoryID is a mock of RepositoryID interface.
type MockRepositoryID struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryIDMockRecorder
	isgomock struct{}
}

// MockRepositoryIDMockRecorder is the mock recorder for MockRepositoryID.
type MockRepositoryIDMockRecorder struct {
	mock *MockRepositoryID
}

// NewMockRepositoryID creates a new mock instance.
func NewMockRepositoryID(ctrl *gomock.Controller) *MockRepositoryID {
	mock := &MockRepositoryID{ctrl: ctrl}
	mock.recorder = &MockRepositoryIDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryID) EXPECT() *MockRepositoryIDMockRecorder {
	return m.recorder
}

// ChangeURL mocks base method.
func (m *MockRepositoryID) ChangeURL(changeID forge.ChangeID) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeURL", changeID)
	ret0, _ := ret[0].(string)
	return ret0
}

// ChangeURL indicates an expected call of ChangeURL.
func (mr *MockRepositoryIDMockRecorder) ChangeURL(changeID any) *MockRepositoryIDChangeURLCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeURL", reflect.TypeOf((*MockRepositoryID)(nil).ChangeURL), changeID)
	return &MockRepositoryIDChangeURLCall{Call: call}
}

// MockRepositoryIDChangeURLCall wrap *gomock.Call
type MockRepositoryIDChangeURLCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryIDChangeURLCall) Return(arg0 string) *MockRepositoryIDChangeURLCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryIDChangeURLCall) Do(f func(forge.ChangeID) string) *MockRepositoryIDChangeURLCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryIDChangeURLCall) DoAndReturn(f func(forge.ChangeID) string) *MockRepositoryIDChangeURLCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// String mocks base method.
func (m *MockRepositoryID) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockRepositoryIDMockRecorder) String() *MockRepositoryIDStringCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockRepositoryID)(nil).String))
	return &MockRepositoryIDStringCall{Call: call}
}

// MockRepositoryIDStringCall wrap *gomock.Call
type MockRepositoryIDStringCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryIDStringCall) Return(arg0 string) *MockRepositoryIDStringCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryIDStringCall) Do(f func() string) *MockRepositoryIDStringCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryIDStringCall) DoAndReturn(f func() string) *MockRepositoryIDStringCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// ChangeChecksState mocks base method.
func (m *MockRepository) ChangeChecksState(ctx context.Context, id forge.ChangeID) (forge.ChecksState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeChecksState", ctx, id)
	ret0, _ := ret[0].(forge.ChecksState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangeChecksState indicates an expected call of ChangeChecksState.
func (mr *MockRepositoryMockRecorder) ChangeChecksState(ctx, id any) *MockRepositoryChangeChecksStateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeChecksState", reflect.TypeOf((*MockRepository)(nil).ChangeChecksState), ctx, id)
	return &MockRepositoryChangeChecksStateCall{Call: call}
}

// MockRepositoryChangeChecksStateCall wrap *gomock.Call
type MockRepositoryChangeChecksStateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryChangeChecksStateCall) Return(arg0 forge.ChecksState, arg1 error) *MockRepositoryChangeChecksStateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryChangeChecksStateCall) Do(f func(context.Context, forge.ChangeID) (forge.ChecksState, error)) *MockRepositoryChangeChecksStateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryChangeChecksStateCall) DoAndReturn(f func(context.Context, forge.ChangeID) (forge.ChecksState, error)) *MockRepositoryChangeChecksStateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ChangeStatuses mocks base method.
func (m *MockRepository) ChangeStatuses(ctx context.Context, ids []forge.ChangeID) ([]forge.ChangeStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeStatuses", ctx, ids)
	ret0, _ := ret[0].([]forge.ChangeStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangeStatuses indicates an expected call of ChangeStatuses.
func (mr *MockRepositoryMockRecorder) ChangeStatuses(ctx, ids any) *MockRepositoryChangeStatusesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeStatuses", reflect.TypeOf((*MockRepository)(nil).ChangeStatuses), ctx, ids)
	return &MockRepositoryChangeStatusesCall{Call: call}
}

// MockRepositoryChangeStatusesCall wrap *gomock.Call
type MockRepositoryChangeStatusesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryChangeStatusesCall) Return(arg0 []forge.ChangeStatus, arg1 error) *MockRepositoryChangeStatusesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryChangeStatusesCall) Do(f func(context.Context, []forge.ChangeID) ([]forge.ChangeStatus, error)) *MockRepositoryChangeStatusesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryChangeStatusesCall) DoAndReturn(f func(context.Context, []forge.ChangeID) ([]forge.ChangeStatus, error)) *MockRepositoryChangeStatusesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CommentCountsByChange mocks base method.
func (m *MockRepository) CommentCountsByChange(ctx context.Context, ids []forge.ChangeID) ([]*forge.CommentCounts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommentCountsByChange", ctx, ids)
	ret0, _ := ret[0].([]*forge.CommentCounts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommentCountsByChange indicates an expected call of CommentCountsByChange.
func (mr *MockRepositoryMockRecorder) CommentCountsByChange(ctx, ids any) *MockRepositoryCommentCountsByChangeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommentCountsByChange", reflect.TypeOf((*MockRepository)(nil).CommentCountsByChange), ctx, ids)
	return &MockRepositoryCommentCountsByChangeCall{Call: call}
}

// MockRepositoryCommentCountsByChangeCall wrap *gomock.Call
type MockRepositoryCommentCountsByChangeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryCommentCountsByChangeCall) Return(arg0 []*forge.CommentCounts, arg1 error) *MockRepositoryCommentCountsByChangeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryCommentCountsByChangeCall) Do(f func(context.Context, []forge.ChangeID) ([]*forge.CommentCounts, error)) *MockRepositoryCommentCountsByChangeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryCommentCountsByChangeCall) DoAndReturn(f func(context.Context, []forge.ChangeID) ([]*forge.CommentCounts, error)) *MockRepositoryCommentCountsByChangeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteChangeComment mocks base method.
func (m *MockRepository) DeleteChangeComment(arg0 context.Context, arg1 forge.ChangeCommentID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChangeComment", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChangeComment indicates an expected call of DeleteChangeComment.
func (mr *MockRepositoryMockRecorder) DeleteChangeComment(arg0, arg1 any) *MockRepositoryDeleteChangeCommentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChangeComment", reflect.TypeOf((*MockRepository)(nil).DeleteChangeComment), arg0, arg1)
	return &MockRepositoryDeleteChangeCommentCall{Call: call}
}

// MockRepositoryDeleteChangeCommentCall wrap *gomock.Call
type MockRepositoryDeleteChangeCommentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryDeleteChangeCommentCall) Return(arg0 error) *MockRepositoryDeleteChangeCommentCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryDeleteChangeCommentCall) Do(f func(context.Context, forge.ChangeCommentID) error) *MockRepositoryDeleteChangeCommentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryDeleteChangeCommentCall) DoAndReturn(f func(context.Context, forge.ChangeCommentID) error) *MockRepositoryDeleteChangeCommentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// EditChange mocks base method.
func (m *MockRepository) EditChange(ctx context.Context, id forge.ChangeID, opts forge.EditChangeOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditChange", ctx, id, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// EditChange indicates an expected call of EditChange.
func (mr *MockRepositoryMockRecorder) EditChange(ctx, id, opts any) *MockRepositoryEditChangeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditChange", reflect.TypeOf((*MockRepository)(nil).EditChange), ctx, id, opts)
	return &MockRepositoryEditChangeCall{Call: call}
}

// MockRepositoryEditChangeCall wrap *gomock.Call
type MockRepositoryEditChangeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryEditChangeCall) Return(arg0 error) *MockRepositoryEditChangeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryEditChangeCall) Do(f func(context.Context, forge.ChangeID, forge.EditChangeOptions) error) *MockRepositoryEditChangeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryEditChangeCall) DoAndReturn(f func(context.Context, forge.ChangeID, forge.EditChangeOptions) error) *MockRepositoryEditChangeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// EditComment mocks base method.
func (m *MockRepository) EditComment(arg0 context.Context, arg1 forge.ChangeCommentID, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditComment", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// EditComment indicates an expected call of EditComment.
func (mr *MockRepositoryMockRecorder) EditComment(arg0, arg1, arg2 any) *MockRepositoryEditCommentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditComment", reflect.TypeOf((*MockRepository)(nil).EditComment), arg0, arg1, arg2)
	return &MockRepositoryEditCommentCall{Call: call}
}

// MockRepositoryEditCommentCall wrap *gomock.Call
type MockRepositoryEditCommentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryEditCommentCall) Return(arg0 error) *MockRepositoryEditCommentCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryEditCommentCall) Do(f func(context.Context, forge.ChangeCommentID, string) error) *MockRepositoryEditCommentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryEditCommentCall) DoAndReturn(f func(context.Context, forge.ChangeCommentID, string) error) *MockRepositoryEditCommentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindChangeByID mocks base method.
func (m *MockRepository) FindChangeByID(ctx context.Context, id forge.ChangeID) (*forge.FindChangeItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindChangeByID", ctx, id)
	ret0, _ := ret[0].(*forge.FindChangeItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindChangeByID indicates an expected call of FindChangeByID.
func (mr *MockRepositoryMockRecorder) FindChangeByID(ctx, id any) *MockRepositoryFindChangeByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindChangeByID", reflect.TypeOf((*MockRepository)(nil).FindChangeByID), ctx, id)
	return &MockRepositoryFindChangeByIDCall{Call: call}
}

// MockRepositoryFindChangeByIDCall wrap *gomock.Call
type MockRepositoryFindChangeByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryFindChangeByIDCall) Return(arg0 *forge.FindChangeItem, arg1 error) *MockRepositoryFindChangeByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryFindChangeByIDCall) Do(f func(context.Context, forge.ChangeID) (*forge.FindChangeItem, error)) *MockRepositoryFindChangeByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryFindChangeByIDCall) DoAndReturn(f func(context.Context, forge.ChangeID) (*forge.FindChangeItem, error)) *MockRepositoryFindChangeByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindChangesByBranch mocks base method.
func (m *MockRepository) FindChangesByBranch(ctx context.Context, branch string, opts forge.FindChangesOptions) ([]*forge.FindChangeItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindChangesByBranch", ctx, branch, opts)
	ret0, _ := ret[0].([]*forge.FindChangeItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindChangesByBranch indicates an expected call of FindChangesByBranch.
func (mr *MockRepositoryMockRecorder) FindChangesByBranch(ctx, branch, opts any) *MockRepositoryFindChangesByBranchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindChangesByBranch", reflect.TypeOf((*MockRepository)(nil).FindChangesByBranch), ctx, branch, opts)
	return &MockRepositoryFindChangesByBranchCall{Call: call}
}

// MockRepositoryFindChangesByBranchCall wrap *gomock.Call
type MockRepositoryFindChangesByBranchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryFindChangesByBranchCall) Return(arg0 []*forge.FindChangeItem, arg1 error) *MockRepositoryFindChangesByBranchCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryFindChangesByBranchCall) Do(f func(context.Context, string, forge.FindChangesOptions) ([]*forge.FindChangeItem, error)) *MockRepositoryFindChangesByBranchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryFindChangesByBranchCall) DoAndReturn(f func(context.Context, string, forge.FindChangesOptions) ([]*forge.FindChangeItem, error)) *MockRepositoryFindChangesByBranchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Forge mocks base method.
func (m *MockRepository) Forge() forge.Forge {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Forge")
	ret0, _ := ret[0].(forge.Forge)
	return ret0
}

// Forge indicates an expected call of Forge.
func (mr *MockRepositoryMockRecorder) Forge() *MockRepositoryForgeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Forge", reflect.TypeOf((*MockRepository)(nil).Forge))
	return &MockRepositoryForgeCall{Call: call}
}

// MockRepositoryForgeCall wrap *gomock.Call
type MockRepositoryForgeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryForgeCall) Return(arg0 forge.Forge) *MockRepositoryForgeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryForgeCall) Do(f func() forge.Forge) *MockRepositoryForgeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryForgeCall) DoAndReturn(f func() forge.Forge) *MockRepositoryForgeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListChangeComments mocks base method.
func (m *MockRepository) ListChangeComments(arg0 context.Context, arg1 forge.ChangeID, arg2 *forge.ListChangeCommentsOptions) iter.Seq2[*forge.ListChangeCommentItem, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChangeComments", arg0, arg1, arg2)
	ret0, _ := ret[0].(iter.Seq2[*forge.ListChangeCommentItem, error])
	return ret0
}

// ListChangeComments indicates an expected call of ListChangeComments.
func (mr *MockRepositoryMockRecorder) ListChangeComments(arg0, arg1, arg2 any) *MockRepositoryListChangeCommentsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChangeComments", reflect.TypeOf((*MockRepository)(nil).ListChangeComments), arg0, arg1, arg2)
	return &MockRepositoryListChangeCommentsCall{Call: call}
}

// MockRepositoryListChangeCommentsCall wrap *gomock.Call
type MockRepositoryListChangeCommentsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryListChangeCommentsCall) Return(arg0 iter.Seq2[*forge.ListChangeCommentItem, error]) *MockRepositoryListChangeCommentsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryListChangeCommentsCall) Do(f func(context.Context, forge.ChangeID, *forge.ListChangeCommentsOptions) iter.Seq2[*forge.ListChangeCommentItem, error]) *MockRepositoryListChangeCommentsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryListChangeCommentsCall) DoAndReturn(f func(context.Context, forge.ChangeID, *forge.ListChangeCommentsOptions) iter.Seq2[*forge.ListChangeCommentItem, error]) *MockRepositoryListChangeCommentsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListChangeTemplates mocks base method.
func (m *MockRepository) ListChangeTemplates(arg0 context.Context) ([]*forge.ChangeTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChangeTemplates", arg0)
	ret0, _ := ret[0].([]*forge.ChangeTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChangeTemplates indicates an expected call of ListChangeTemplates.
func (mr *MockRepositoryMockRecorder) ListChangeTemplates(arg0 any) *MockRepositoryListChangeTemplatesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChangeTemplates", reflect.TypeOf((*MockRepository)(nil).ListChangeTemplates), arg0)
	return &MockRepositoryListChangeTemplatesCall{Call: call}
}

// MockRepositoryListChangeTemplatesCall wrap *gomock.Call
type MockRepositoryListChangeTemplatesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryListChangeTemplatesCall) Return(arg0 []*forge.ChangeTemplate, arg1 error) *MockRepositoryListChangeTemplatesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryListChangeTemplatesCall) Do(f func(context.Context) ([]*forge.ChangeTemplate, error)) *MockRepositoryListChangeTemplatesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryListChangeTemplatesCall) DoAndReturn(f func(context.Context) ([]*forge.ChangeTemplate, error)) *MockRepositoryListChangeTemplatesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MergeChange mocks base method.
func (m *MockRepository) MergeChange(ctx context.Context, id forge.ChangeID, opts forge.MergeChangeOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergeChange", ctx, id, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// MergeChange indicates an expected call of MergeChange.
func (mr *MockRepositoryMockRecorder) MergeChange(ctx, id, opts any) *MockRepositoryMergeChangeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergeChange", reflect.TypeOf((*MockRepository)(nil).MergeChange), ctx, id, opts)
	return &MockRepositoryMergeChangeCall{Call: call}
}

// MockRepositoryMergeChangeCall wrap *gomock.Call
type MockRepositoryMergeChangeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryMergeChangeCall) Return(arg0 error) *MockRepositoryMergeChangeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryMergeChangeCall) Do(f func(context.Context, forge.ChangeID, forge.MergeChangeOptions) error) *MockRepositoryMergeChangeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryMergeChangeCall) DoAndReturn(f func(context.Context, forge.ChangeID, forge.MergeChangeOptions) error) *MockRepositoryMergeChangeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// NewChangeMetadata mocks base method.
func (m *MockRepository) NewChangeMetadata(ctx context.Context, id forge.ChangeID) (forge.ChangeMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewChangeMetadata", ctx, id)
	ret0, _ := ret[0].(forge.ChangeMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewChangeMetadata indicates an expected call of NewChangeMetadata.
func (mr *MockRepositoryMockRecorder) NewChangeMetadata(ctx, id any) *MockRepositoryNewChangeMetadataCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewChangeMetadata", reflect.TypeOf((*MockRepository)(nil).NewChangeMetadata), ctx, id)
	return &MockRepositoryNewChangeMetadataCall{Call: call}
}

// MockRepositoryNewChangeMetadataCall wrap *gomock.Call
type MockRepositoryNewChangeMetadataCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryNewChangeMetadataCall) Return(arg0 forge.ChangeMetadata, arg1 error) *MockRepositoryNewChangeMetadataCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryNewChangeMetadataCall) Do(f func(context.Context, forge.ChangeID) (forge.ChangeMetadata, error)) *MockRepositoryNewChangeMetadataCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryNewChangeMetadataCall) DoAndReturn(f func(context.Context, forge.ChangeID) (forge.ChangeMetadata, error)) *MockRepositoryNewChangeMetadataCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PostChangeComment mocks base method.
func (m *MockRepository) PostChangeComment(arg0 context.Context, arg1 forge.ChangeID, arg2 string) (forge.ChangeCommentID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostChangeComment", arg0, arg1, arg2)
	ret0, _ := ret[0].(forge.ChangeCommentID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostChangeComment indicates an expected call of PostChangeComment.
func (mr *MockRepositoryMockRecorder) PostChangeComment(arg0, arg1, arg2 any) *MockRepositoryPostChangeCommentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostChangeComment", reflect.TypeOf((*MockRepository)(nil).PostChangeComment), arg0, arg1, arg2)
	return &MockRepositoryPostChangeCommentCall{Call: call}
}

// MockRepositoryPostChangeCommentCall wrap *gomock.Call
type MockRepositoryPostChangeCommentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryPostChangeCommentCall) Return(arg0 forge.ChangeCommentID, arg1 error) *MockRepositoryPostChangeCommentCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryPostChangeCommentCall) Do(f func(context.Context, forge.ChangeID, string) (forge.ChangeCommentID, error)) *MockRepositoryPostChangeCommentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryPostChangeCommentCall) DoAndReturn(f func(context.Context, forge.ChangeID, string) (forge.ChangeCommentID, error)) *MockRepositoryPostChangeCommentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SubmitChange mocks base method.
func (m *MockRepository) SubmitChange(ctx context.Context, req forge.SubmitChangeRequest) (forge.SubmitChangeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitChange", ctx, req)
	ret0, _ := ret[0].(forge.SubmitChangeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitChange indicates an expected call of SubmitChange.
func (mr *MockRepositoryMockRecorder) SubmitChange(ctx, req any) *MockRepositorySubmitChangeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitChange", reflect.TypeOf((*MockRepository)(nil).SubmitChange), ctx, req)
	return &MockRepositorySubmitChangeCall{Call: call}
}

// MockRepositorySubmitChangeCall wrap *gomock.Call
type MockRepositorySubmitChangeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositorySubmitChangeCall) Return(arg0 forge.SubmitChangeResult, arg1 error) *MockRepositorySubmitChangeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositorySubmitChangeCall) Do(f func(context.Context, forge.SubmitChangeRequest) (forge.SubmitChangeResult, error)) *MockRepositorySubmitChangeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositorySubmitChangeCall) DoAndReturn(f func(context.Context, forge.SubmitChangeRequest) (forge.SubmitChangeResult, error)) *MockRepositorySubmitChangeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateChangeComment mocks base method.
func (m *MockRepository) UpdateChangeComment(arg0 context.Context, arg1 forge.ChangeCommentID, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateChangeComment", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateChangeComment indicates an expected call of UpdateChangeComment.
func (mr *MockRepositoryMockRecorder) UpdateChangeComment(arg0, arg1, arg2 any) *MockRepositoryUpdateChangeCommentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateChangeComment", reflect.TypeOf((*MockRepository)(nil).UpdateChangeComment), arg0, arg1, arg2)
	return &MockRepositoryUpdateChangeCommentCall{Call: call}
}

// MockRepositoryUpdateChangeCommentCall wrap *gomock.Call
type MockRepositoryUpdateChangeCommentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryUpdateChangeCommentCall) Return(arg0 error) *MockRepositoryUpdateChangeCommentCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryUpdateChangeCommentCall) Do(f func(context.Context, forge.ChangeCommentID, string) error) *MockRepositoryUpdateChangeCommentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryUpdateChangeCommentCall) DoAndReturn(f func(context.Context, forge.ChangeCommentID, string) error) *MockRepositoryUpdateChangeCommentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockWithInlineComments is a mock of WithInlineComments interface.
type MockWithInlineComments struct {
	ctrl     *gomock.Controller
	recorder *MockWithInlineCommentsMockRecorder
	isgomock struct{}
}

// MockWithInlineCommentsMockRecorder is the mock recorder for MockWithInlineComments.
type MockWithInlineCommentsMockRecorder struct {
	mock *MockWithInlineComments
}

// NewMockWithInlineComments creates a new mock instance.
func NewMockWithInlineComments(ctrl *gomock.Controller) *MockWithInlineComments {
	mock := &MockWithInlineComments{ctrl: ctrl}
	mock.recorder = &MockWithInlineCommentsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWithInlineComments) EXPECT() *MockWithInlineCommentsMockRecorder {
	return m.recorder
}

// ChangeChecksState mocks base method.
func (m *MockWithInlineComments) ChangeChecksState(ctx context.Context, id forge.ChangeID) (forge.ChecksState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeChecksState", ctx, id)
	ret0, _ := ret[0].(forge.ChecksState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangeChecksState indicates an expected call of ChangeChecksState.
func (mr *MockWithInlineCommentsMockRecorder) ChangeChecksState(ctx, id any) *MockWithInlineCommentsChangeChecksStateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeChecksState", reflect.TypeOf((*MockWithInlineComments)(nil).ChangeChecksState), ctx, id)
	return &MockWithInlineCommentsChangeChecksStateCall{Call: call}
}

// MockWithInlineCommentsChangeChecksStateCall wrap *gomock.Call
type MockWithInlineCommentsChangeChecksStateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWithInlineCommentsChangeChecksStateCall) Return(arg0 forge.ChecksState, arg1 error) *MockWithInlineCommentsChangeChecksStateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWithInlineCommentsChangeChecksStateCall) Do(f func(context.Context, forge.ChangeID) (forge.ChecksState, error)) *MockWithInlineCommentsChangeChecksStateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWithInlineCommentsChangeChecksStateCall) DoAndReturn(f func(context.Context, forge.ChangeID) (forge.ChecksState, error)) *MockWithInlineCommentsChangeChecksStateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ChangeStatuses mocks base method.
func (m *MockWithInlineComments) ChangeStatuses(ctx context.Context, ids []forge.ChangeID) ([]forge.ChangeStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeStatuses", ctx, ids)
	ret0, _ := ret[0].([]forge.ChangeStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangeStatuses indicates an expected call of ChangeStatuses.
func (mr *MockWithInlineCommentsMockRecorder) ChangeStatuses(ctx, ids any) *MockWithInlineCommentsChangeStatusesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeStatuses", reflect.TypeOf((*MockWithInlineComments)(nil).ChangeStatuses), ctx, ids)
	return &MockWithInlineCommentsChangeStatusesCall{Call: call}
}

// MockWithInlineCommentsChangeStatusesCall wrap *gomock.Call
type MockWithInlineCommentsChangeStatusesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWithInlineCommentsChangeStatusesCall) Return(arg0 []forge.ChangeStatus, arg1 error) *MockWithInlineCommentsChangeStatusesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWithInlineCommentsChangeStatusesCall) Do(f func(context.Context, []forge.ChangeID) ([]forge.ChangeStatus, error)) *MockWithInlineCommentsChangeStatusesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWithInlineCommentsChangeStatusesCall) DoAndReturn(f func(context.Context, []forge.ChangeID) ([]forge.ChangeStatus, error)) *MockWithInlineCommentsChangeStatusesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CommentCountsByChange mocks base method.
func (m *MockWithInlineComments) CommentCountsByChange(ctx context.Context, ids []forge.ChangeID) ([]*forge.CommentCounts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommentCountsByChange", ctx, ids)
	ret0, _ := ret[0].([]*forge.CommentCounts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommentCountsByChange indicates an expected call of CommentCountsByChange.
func (mr *MockWithInlineCommentsMockRecorder) CommentCountsByChange(ctx, ids any) *MockWithInlineCommentsCommentCountsByChangeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommentCountsByChange", reflect.TypeOf((*MockWithInlineComments)(nil).CommentCountsByChange), ctx, ids)
	return &MockWithInlineCommentsCommentCountsByChangeCall{Call: call}
}

// MockWithInlineCommentsCommentCountsByChangeCall wrap *gomock.Call
type MockWithInlineCommentsCommentCountsByChangeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWithInlineCommentsCommentCountsByChangeCall) Return(arg0 []*forge.CommentCounts, arg1 error) *MockWithInlineCommentsCommentCountsByChangeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWithInlineCommentsCommentCountsByChangeCall) Do(f func(context.Context, []forge.ChangeID) ([]*forge.CommentCounts, error)) *MockWithInlineCommentsCommentCountsByChangeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWithInlineCommentsCommentCountsByChangeCall) DoAndReturn(f func(context.Context, []forge.ChangeID) ([]*forge.CommentCounts, error)) *MockWithInlineCommentsCommentCountsByChangeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteChangeComment mocks base method.
func (m *MockWithInlineComments) DeleteChangeComment(arg0 context.Context, arg1 forge.ChangeCommentID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChangeComment", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChangeComment indicates an expected call of DeleteChangeComment.
func (mr *MockWithInlineCommentsMockRecorder) DeleteChangeComment(arg0, arg1 any) *MockWithInlineCommentsDeleteChangeCommentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChangeComment", reflect.TypeOf((*MockWithInlineComments)(nil).DeleteChangeComment), arg0, arg1)
	return &MockWithInlineCommentsDeleteChangeCommentCall{Call: call}
}

// MockWithInlineCommentsDeleteChangeCommentCall wrap *gomock.Call
type MockWithInlineCommentsDeleteChangeCommentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWithInlineCommentsDeleteChangeCommentCall) Return(arg0 error) *MockWithInlineCommentsDeleteChangeCommentCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWithInlineCommentsDeleteChangeCommentCall) Do(f func(context.Context, forge.ChangeCommentID) error) *MockWithInlineCommentsDeleteChangeCommentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWithInlineCommentsDeleteChangeCommentCall) DoAndReturn(f func(context.Context, forge.ChangeCommentID) error) *MockWithInlineCommentsDeleteChangeCommentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// EditChange mocks base method.
func (m *MockWithInlineComments) EditChange(ctx context.Context, id forge.ChangeID, opts forge.EditChangeOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditChange", ctx, id, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// EditChange indicates an expected call of EditChange.
func (mr *MockWithInlineCommentsMockRecorder) EditChange(ctx, id, opts any) *MockWithInlineCommentsEditChangeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditChange", reflect.TypeOf((*MockWithInlineComments)(nil).EditChange), ctx, id, opts)
	return &MockWithInlineCommentsEditChangeCall{Call: call}
}

// MockWithInlineCommentsEditChangeCall wrap *gomock.Call
type MockWithInlineCommentsEditChangeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWithInlineCommentsEditChangeCall) Return(arg0 error) *MockWithInlineCommentsEditChangeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWithInlineCommentsEditChangeCall) Do(f func(context.Context, forge.ChangeID, forge.EditChangeOptions) error) *MockWithInlineCommentsEditChangeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWithInlineCommentsEditChangeCall) DoAndReturn(f func(context.Context, forge.ChangeID, forge.EditChangeOptions) error) *MockWithInlineCommentsEditChangeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// EditComment mocks base method.
func (m *MockWithInlineComments) EditComment(arg0 context.Context, arg1 forge.ChangeCommentID, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditComment", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// EditComment indicates an expected call of EditComment.
func (mr *MockWithInlineCommentsMockRecorder) EditComment(arg0, arg1, arg2 any) *MockWithInlineCommentsEditCommentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditComment", reflect.TypeOf((*MockWithInlineComments)(nil).EditComment), arg0, arg1, arg2)
	return &MockWithInlineCommentsEditCommentCall{Call: call}
}

// MockWithInlineCommentsEditCommentCall wrap *gomock.Call
type MockWithInlineCommentsEditCommentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWithInlineCommentsEditCommentCall) Return(arg0 error) *MockWithInlineCommentsEditCommentCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWithInlineCommentsEditCommentCall) Do(f func(context.Context, forge.ChangeCommentID, string) error) *MockWithInlineCommentsEditCommentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWithInlineCommentsEditCommentCall) DoAndReturn(f func(context.Context, forge.ChangeCommentID, string) error) *MockWithInlineCommentsEditCommentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindChangeByID mocks base method.
func (m *MockWithInlineComments) FindChangeByID(ctx context.Context, id forge.ChangeID) (*forge.FindChangeItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindChangeByID", ctx, id)
	ret0, _ := ret[0].(*forge.FindChangeItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindChangeByID indicates an expected call of FindChangeByID.
func (mr *MockWithInlineCommentsMockRecorder) FindChangeByID(ctx, id any) *MockWithInlineCommentsFindChangeByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindChangeByID", reflect.TypeOf((*MockWithInlineComments)(nil).FindChangeByID), ctx, id)
	return &MockWithInlineCommentsFindChangeByIDCall{Call: call}
}

// MockWithInlineCommentsFindChangeByIDCall wrap *gomock.Call
type MockWithInlineCommentsFindChangeByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWithInlineCommentsFindChangeByIDCall) Return(arg0 *forge.FindChangeItem, arg1 error) *MockWithInlineCommentsFindChangeByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWithInlineCommentsFindChangeByIDCall) Do(f func(context.Context, forge.ChangeID) (*forge.FindChangeItem, error)) *MockWithInlineCommentsFindChangeByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWithInlineCommentsFindChangeByIDCall) DoAndReturn(f func(context.Context, forge.ChangeID) (*forge.FindChangeItem, error)) *MockWithInlineCommentsFindChangeByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindChangesByBranch mocks base method.
func (m *MockWithInlineComments) FindChangesByBranch(ctx context.Context, branch string, opts forge.FindChangesOptions) ([]*forge.FindChangeItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindChangesByBranch", ctx, branch, opts)
	ret0, _ := ret[0].([]*forge.FindChangeItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindChangesByBranch indicates an expected call of FindChangesByBranch.
func (mr *MockWithInlineCommentsMockRecorder) FindChangesByBranch(ctx, branch, opts any) *MockWithInlineCommentsFindChangesByBranchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindChangesByBranch", reflect.TypeOf((*MockWithInlineComments)(nil).FindChangesByBranch), ctx, branch, opts)
	return &MockWithInlineCommentsFindChangesByBranchCall{Call: call}
}

// MockWithInlineCommentsFindChangesByBranchCall wrap *gomock.Call
type MockWithInlineCommentsFindChangesByBranchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWithInlineCommentsFindChangesByBranchCall) Return(arg0 []*forge.FindChangeItem, arg1 error) *MockWithInlineCommentsFindChangesByBranchCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWithInlineCommentsFindChangesByBranchCall) Do(f func(context.Context, string, forge.FindChangesOptions) ([]*forge.FindChangeItem, error)) *MockWithInlineCommentsFindChangesByBranchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWithInlineCommentsFindChangesByBranchCall) DoAndReturn(f func(context.Context, string, forge.FindChangesOptions) ([]*forge.FindChangeItem, error)) *MockWithInlineCommentsFindChangesByBranchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Forge mocks base method.
func (m *MockWithInlineComments) Forge() forge.Forge {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Forge")
	ret0, _ := ret[0].(forge.Forge)
	return ret0
}

// Forge indicates an expected call of Forge.
func (mr *MockWithInlineCommentsMockRecorder) Forge() *MockWithInlineCommentsForgeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Forge", reflect.TypeOf((*MockWithInlineComments)(nil).Forge))
	return &MockWithInlineCommentsForgeCall{Call: call}
}

// MockWithInlineCommentsForgeCall wrap *gomock.Call
type MockWithInlineCommentsForgeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWithInlineCommentsForgeCall) Return(arg0 forge.Forge) *MockWithInlineCommentsForgeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWithInlineCommentsForgeCall) Do(f func() forge.Forge) *MockWithInlineCommentsForgeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWithInlineCommentsForgeCall) DoAndReturn(f func() forge.Forge) *MockWithInlineCommentsForgeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListChangeComments mocks base method.
func (m *MockWithInlineComments) ListChangeComments(arg0 context.Context, arg1 forge.ChangeID, arg2 *forge.ListChangeCommentsOptions) iter.Seq2[*forge.ListChangeCommentItem, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChangeComments", arg0, arg1, arg2)
	ret0, _ := ret[0].(iter.Seq2[*forge.ListChangeCommentItem, error])
	return ret0
}

// ListChangeComments indicates an expected call of ListChangeComments.
func (mr *MockWithInlineCommentsMockRecorder) ListChangeComments(arg0, arg1, arg2 any) *MockWithInlineCommentsListChangeCommentsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChangeComments", reflect.TypeOf((*MockWithInlineComments)(nil).ListChangeComments), arg0, arg1, arg2)
	return &MockWithInlineCommentsListChangeCommentsCall{Call: call}
}

// MockWithInlineCommentsListChangeCommentsCall wrap *gomock.Call
type MockWithInlineCommentsListChangeCommentsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWithInlineCommentsListChangeCommentsCall) Return(arg0 iter.Seq2[*forge.ListChangeCommentItem, error]) *MockWithInlineCommentsListChangeCommentsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWithInlineCommentsListChangeCommentsCall) Do(f func(context.Context, forge.ChangeID, *forge.ListChangeCommentsOptions) iter.Seq2[*forge.ListChangeCommentItem, error]) *MockWithInlineCommentsListChangeCommentsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWithInlineCommentsListChangeCommentsCall) DoAndReturn(f func(context.Context, forge.ChangeID, *forge.ListChangeCommentsOptions) iter.Seq2[*forge.ListChangeCommentItem, error]) *MockWithInlineCommentsListChangeCommentsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListChangeTemplates mocks base method.
func (m *MockWithInlineComments) ListChangeTemplates(arg0 context.Context) ([]*forge.ChangeTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChangeTemplates", arg0)
	ret0, _ := ret[0].([]*forge.ChangeTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChangeTemplates indicates an expected call of ListChangeTemplates.
func (mr *MockWithInlineCommentsMockRecorder) ListChangeTemplates(arg0 any) *MockWithInlineCommentsListChangeTemplatesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChangeTemplates", reflect.TypeOf((*MockWithInlineComments)(nil).ListChangeTemplates), arg0)
	return &MockWithInlineCommentsListChangeTemplatesCall{Call: call}
}

// MockWithInlineCommentsListChangeTemplatesCall wrap *gomock.Call
type MockWithInlineCommentsListChangeTemplatesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWithInlineCommentsListChangeTemplatesCall) Return(arg0 []*forge.ChangeTemplate, arg1 error) *MockWithInlineCommentsListChangeTemplatesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWithInlineCommentsListChangeTemplatesCall) Do(f func(context.Context) ([]*forge.ChangeTemplate, error)) *MockWithInlineCommentsListChangeTemplatesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWithInlineCommentsListChangeTemplatesCall) DoAndReturn(f func(context.Context) ([]*forge.ChangeTemplate, error)) *MockWithInlineCommentsListChangeTemplatesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListInlineComments mocks base method.
func (m *MockWithInlineComments) ListInlineComments(ctx context.Context, id forge.ChangeID) ([]*forge.InlineComment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInlineComments", ctx, id)
	ret0, _ := ret[0].([]*forge.InlineComment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInlineComments indicates an expected call of ListInlineComments.
func (mr *MockWithInlineCommentsMockRecorder) ListInlineComments(ctx, id any) *MockWithInlineCommentsListInlineCommentsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInlineComments", reflect.TypeOf((*MockWithInlineComments)(nil).ListInlineComments), ctx, id)
	return &MockWithInlineCommentsListInlineCommentsCall{Call: call}
}

// MockWithInlineCommentsListInlineCommentsCall wrap *gomock.Call
type MockWithInlineCommentsListInlineCommentsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWithInlineCommentsListInlineCommentsCall) Return(arg0 []*forge.InlineComment, arg1 error) *MockWithInlineCommentsListInlineCommentsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWithInlineCommentsListInlineCommentsCall) Do(f func(context.Context, forge.ChangeID) ([]*forge.InlineComment, error)) *MockWithInlineCommentsListInlineCommentsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWithInlineCommentsListInlineCommentsCall) DoAndReturn(f func(context.Context, forge.ChangeID) ([]*forge.InlineComment, error)) *MockWithInlineCommentsListInlineCommentsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MergeChange mocks base method.
func (m *MockWithInlineComments) MergeChange(ctx context.Context, id forge.ChangeID, opts forge.MergeChangeOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergeChange", ctx, id, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// MergeChange indicates an expected call of MergeChange.
func (mr *MockWithInlineCommentsMockRecorder) MergeChange(ctx, id, opts any) *MockWithInlineCommentsMergeChangeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergeChange", reflect.TypeOf((*MockWithInlineComments)(nil).MergeChange), ctx, id, opts)
	return &MockWithInlineCommentsMergeChangeCall{Call: call}
}

// MockWithInlineCommentsMergeChangeCall wrap *gomock.Call
type MockWithInlineCommentsMergeChangeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWithInlineCommentsMergeChangeCall) Return(arg0 error) *MockWithInlineCommentsMergeChangeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWithInlineCommentsMergeChangeCall) Do(f func(context.Context, forge.ChangeID, forge.MergeChangeOptions) error) *MockWithInlineCommentsMergeChangeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWithInlineCommentsMergeChangeCall) DoAndReturn(f func(context.Context, forge.ChangeID, forge.MergeChangeOptions) error) *MockWithInlineCommentsMergeChangeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// NewChangeMetadata mocks base method.
func (m *MockWithInlineComments) NewChangeMetadata(ctx context.Context, id forge.ChangeID) (forge.ChangeMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewChangeMetadata", ctx, id)
	ret0, _ := ret[0].(forge.ChangeMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewChangeMetadata indicates an expected call of NewChangeMetadata.
func (mr *MockWithInlineCommentsMockRecorder) NewChangeMetadata(ctx, id any) *MockWithInlineCommentsNewChangeMetadataCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewChangeMetadata", reflect.TypeOf((*MockWithInlineComments)(nil).NewChangeMetadata), ctx, id)
	return &MockWithInlineCommentsNewChangeMetadataCall{Call: call}
}

// MockWithInlineCommentsNewChangeMetadataCall wrap *gomock.Call
type MockWithInlineCommentsNewChangeMetadataCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWithInlineCommentsNewChangeMetadataCall) Return(arg0 forge.ChangeMetadata, arg1 error) *MockWithInlineCommentsNewChangeMetadataCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWithInlineCommentsNewChangeMetadataCall) Do(f func(context.Context, forge.ChangeID) (forge.ChangeMetadata, error)) *MockWithInlineCommentsNewChangeMetadataCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWithInlineCommentsNewChangeMetadataCall) DoAndReturn(f func(context.Context, forge.ChangeID) (forge.ChangeMetadata, error)) *MockWithInlineCommentsNewChangeMetadataCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PostChangeComment mocks base method.
func (m *MockWithInlineComments) PostChangeComment(arg0 context.Context, arg1 forge.ChangeID, arg2 string) (forge.ChangeCommentID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostChangeComment", arg0, arg1, arg2)
	ret0, _ := ret[0].(forge.ChangeCommentID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostChangeComment indicates an expected call of PostChangeComment.
func (mr *MockWithInlineCommentsMockRecorder) PostChangeComment(arg0, arg1, arg2 any) *MockWithInlineCommentsPostChangeCommentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostChangeComment", reflect.TypeOf((*MockWithInlineComments)(nil).PostChangeComment), arg0, arg1, arg2)
	return &MockWithInlineCommentsPostChangeCommentCall{Call: call}
}

// MockWithInlineCommentsPostChangeCommentCall wrap *gomock.Call
type MockWithInlineCommentsPostChangeCommentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWithInlineCommentsPostChangeCommentCall) Return(arg0 forge.ChangeCommentID, arg1 error) *MockWithInlineCommentsPostChangeCommentCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWithInlineCommentsPostChangeCommentCall) Do(f func(context.Context, forge.ChangeID, string) (forge.ChangeCommentID, error)) *MockWithInlineCommentsPostChangeCommentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWithInlineCommentsPostChangeCommentCall) DoAndReturn(f func(context.Context, forge.ChangeID, string) (forge.ChangeCommentID, error)) *MockWithInlineCommentsPostChangeCommentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PostInlineComment mocks base method.
func (m *MockWithInlineComments) PostInlineComment(ctx context.Context, id forge.ChangeID, req forge.InlineCommentRequest) (*forge.InlineComment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostInlineComment", ctx, id, req)
	ret0, _ := ret[0].(*forge.InlineComment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostInlineComment indicates an expected call of PostInlineComment.
func (mr *MockWithInlineCommentsMockRecorder) PostInlineComment(ctx, id, req any) *MockWithInlineCommentsPostInlineCommentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostInlineComment", reflect.TypeOf((*MockWithInlineComments)(nil).PostInlineComment), ctx, id, req)
	return &MockWithInlineCommentsPostInlineCommentCall{Call: call}
}

// MockWithInlineCommentsPostInlineCommentCall wrap *gomock.Call
type MockWithInlineCommentsPostInlineCommentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWithInlineCommentsPostInlineCommentCall) Return(arg0 *forge.InlineComment, arg1 error) *MockWithInlineCommentsPostInlineCommentCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWithInlineCommentsPostInlineCommentCall) Do(f func(context.Context, forge.ChangeID, forge.InlineCommentRequest) (*forge.InlineComment, error)) *MockWithInlineCommentsPostInlineCommentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWithInlineCommentsPostInlineCommentCall) DoAndReturn(f func(context.Context, forge.ChangeID, forge.InlineCommentRequest) (*forge.InlineComment, error)) *MockWithInlineCommentsPostInlineCommentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ResolveThread mocks base method.
func (m *MockWithInlineComments) ResolveThread(ctx context.Context, id forge.InlineCommentThreadID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveThread", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResolveThread indicates an expected call of ResolveThread.
func (mr *MockWithInlineCommentsMockRecorder) ResolveThread(ctx, id any) *MockWithInlineCommentsResolveThreadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveThread", reflect.TypeOf((*MockWithInlineComments)(nil).ResolveThread), ctx, id)
	return &MockWithInlineCommentsResolveThreadCall{Call: call}
}

// MockWithInlineCommentsResolveThreadCall wrap *gomock.Call
type MockWithInlineCommentsResolveThreadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWithInlineCommentsResolveThreadCall) Return(arg0 error) *MockWithInlineCommentsResolveThreadCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWithInlineCommentsResolveThreadCall) Do(f func(context.Context, forge.InlineCommentThreadID) error) *MockWithInlineCommentsResolveThreadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWithInlineCommentsResolveThreadCall) DoAndReturn(f func(context.Context, forge.InlineCommentThreadID) error) *MockWithInlineCommentsResolveThreadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SubmitChange mocks base method.
func (m *MockWithInlineComments) SubmitChange(ctx context.Context, req forge.SubmitChangeRequest) (forge.SubmitChangeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitChange", ctx, req)
	ret0, _ := ret[0].(forge.SubmitChangeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitChange indicates an expected call of SubmitChange.
func (mr *MockWithInlineCommentsMockRecorder) SubmitChange(ctx, req any) *MockWithInlineCommentsSubmitChangeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitChange", reflect.TypeOf((*MockWithInlineComments)(nil).SubmitChange), ctx, req)
	return &MockWithInlineCommentsSubmitChangeCall{Call: call}
}

// MockWithInlineCommentsSubmitChangeCall wrap *gomock.Call
type MockWithInlineCommentsSubmitChangeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWithInlineCommentsSubmitChangeCall) Return(arg0 forge.SubmitChangeResult, arg1 error) *MockWithInlineCommentsSubmitChangeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWithInlineCommentsSubmitChangeCall) Do(f func(context.Context, forge.SubmitChangeRequest) (forge.SubmitChangeResult, error)) *MockWithInlineCommentsSubmitChangeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWithInlineCommentsSubmitChangeCall) DoAndReturn(f func(context.Context, forge.SubmitChangeRequest) (forge.SubmitChangeResult, error)) *MockWithInlineCommentsSubmitChangeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SubmitReview mocks base method.
func (m *MockWithInlineComments) SubmitReview(ctx context.Context, id forge.ChangeID, req forge.ReviewRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitReview", ctx, id, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubmitReview indicates an expected call of SubmitReview.
func (mr *MockWithInlineCommentsMockRecorder) SubmitReview(ctx, id, req any) *MockWithInlineCommentsSubmitReviewCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitReview", reflect.TypeOf((*MockWithInlineComments)(nil).SubmitReview), ctx, id, req)
	return &MockWithInlineCommentsSubmitReviewCall{Call: call}
}

// MockWithInlineCommentsSubmitReviewCall wrap *gomock.Call
type MockWithInlineCommentsSubmitReviewCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWithInlineCommentsSubmitReviewCall) Return(arg0 error) *MockWithInlineCommentsSubmitReviewCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWithInlineCommentsSubmitReviewCall) Do(f func(context.Context, forge.ChangeID, forge.ReviewRequest) error) *MockWithInlineCommentsSubmitReviewCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWithInlineCommentsSubmitReviewCall) DoAndReturn(f func(context.Context, forge.ChangeID, forge.ReviewRequest) error) *MockWithInlineCommentsSubmitReviewCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UnresolveThread mocks base method.
func (m *MockWithInlineComments) UnresolveThread(ctx context.Context, id forge.InlineCommentThreadID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnresolveThread", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnresolveThread indicates an expected call of UnresolveThread.
func (mr *MockWithInlineCommentsMockRecorder) UnresolveThread(ctx, id any) *MockWithInlineCommentsUnresolveThreadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnresolveThread", reflect.TypeOf((*MockWithInlineComments)(nil).UnresolveThread), ctx, id)
	return &MockWithInlineCommentsUnresolveThreadCall{Call: call}
}

// MockWithInlineCommentsUnresolveThreadCall wrap *gomock.Call
type MockWithInlineCommentsUnresolveThreadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWithInlineCommentsUnresolveThreadCall) Return(arg0 error) *MockWithInlineCommentsUnresolveThreadCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWithInlineCommentsUnresolveThreadCall) Do(f func(context.Context, forge.InlineCommentThreadID) error) *MockWithInlineCommentsUnresolveThreadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWithInlineCommentsUnresolveThreadCall) DoAndReturn(f func(context.Context, forge.InlineCommentThreadID) error) *MockWithInlineCommentsUnresolveThreadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateChangeComment mocks base method.
func (m *MockWithInlineComments) UpdateChangeComment(arg0 context.Context, arg1 forge.ChangeCommentID, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateChangeComment", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateChangeComment indicates an expected call of UpdateChangeComment.
func (mr *MockWithInlineCommentsMockRecorder) UpdateChangeComment(arg0, arg1, arg2 any) *MockWithInlineCommentsUpdateChangeCommentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateChangeComment", reflect.TypeOf((*MockWithInlineComments)(nil).UpdateChangeComment), arg0, arg1, arg2)
	return &MockWithInlineCommentsUpdateChangeCommentCall{Call: call}
}

// MockWithInlineCommentsUpdateChangeCommentCall wrap *gomock.Call
type MockWithInlineCommentsUpdateChangeCommentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWithInlineCommentsUpdateChangeCommentCall) Return(arg0 error) *MockWithInlineCommentsUpdateChangeCommentCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWithInlineCommentsUpdateChangeCommentCall) Do(f func(context.Context, forge.ChangeCommentID, string) error) *MockWithInlineCommentsUpdateChangeCommentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWithInlineCommentsUpdateChangeCommentCall) DoAndReturn(f func(context.Context, forge.ChangeCommentID, string) error) *MockWithInlineCommentsUpdateChangeCommentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
