// Code generated by MockGen. DO NOT EDIT.
// Source: go.abhg.dev/gs/internal/handler/integration (interfaces: GitRepository,GitWorktree,Store,Service)
//
// Generated by this command:
//
//	mockgen -typed -destination mocks_test.go -package integration -write_package_comment=false . GitRepository,GitWorktree,Store,Service
//

package integration

import (
	context "context"
	reflect "reflect"

	git "go.abhg.dev/gs/internal/git"
	spice "go.abhg.dev/gs/internal/spice"
	state "go.abhg.dev/gs/internal/spice/state"
	gomock "go.uber.org/mock/gomock"
)

// MockGitRepository is a mock of GitRepository interface.
type MockGitRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGitRepositoryMockRecorder
	isgomock struct{}
}

// MockGitRepositoryMockRecorder is the mock recorder for MockGitRepository.
type MockGitRepositoryMockRecorder struct {
	mock *MockGitRepository
}

// NewMockGitRepository creates a new mock instance.
func NewMockGitRepository(ctrl *gomock.Controller) *MockGitRepository {
	mock := &MockGitRepository{ctrl: ctrl}
	mock.recorder = &MockGitRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitRepository) EXPECT() *MockGitRepositoryMockRecorder {
	return m.recorder
}

// PeelToCommit mocks base method.
func (m *MockGitRepository) PeelToCommit(ctx context.Context, ref string) (git.Hash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PeelToCommit", ctx, ref)
	ret0, _ := ret[0].(git.Hash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PeelToCommit indicates an expected call of PeelToCommit.
func (mr *MockGitRepositoryMockRecorder) PeelToCommit(ctx, ref any) *MockGitRepositoryPeelToCommitCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PeelToCommit", reflect.TypeOf((*MockGitRepository)(nil).PeelToCommit), ctx, ref)
	return &MockGitRepositoryPeelToCommitCall{Call: call}
}

// MockGitRepositoryPeelToCommitCall wrap *gomock.Call
type MockGitRepositoryPeelToCommitCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGitRepositoryPeelToCommitCall) Return(arg0 git.Hash, arg1 error) *MockGitRepositoryPeelToCommitCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGitRepositoryPeelToCommitCall) Do(f func(context.Context, string) (git.Hash, error)) *MockGitRepositoryPeelToCommitCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGitRepositoryPeelToCommitCall) DoAndReturn(f func(context.Context, string) (git.Hash, error)) *MockGitRepositoryPeelToCommitCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockGitWorktree is a mock of GitWorktree interface.
type MockGitWorktree struct {
	ctrl     *gomock.Controller
	recorder *MockGitWorktreeMockRecorder
	isgomock struct{}
}

// MockGitWorktreeMockRecorder is the mock recorder for MockGitWorktree.
type MockGitWorktreeMockRecorder struct {
	mock *MockGitWorktree
}

// NewMockGitWorktree creates a new mock instance.
func NewMockGitWorktree(ctrl *gomock.Controller) *MockGitWorktree {
	mock := &MockGitWorktree{ctrl: ctrl}
	mock.recorder = &MockGitWorktreeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitWorktree) EXPECT() *MockGitWorktreeMockRecorder {
	return m.recorder
}

// CheckoutBranch mocks base method.
func (m *MockGitWorktree) CheckoutBranch(ctx context.Context, branch string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckoutBranch", ctx, branch)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckoutBranch indicates an expected call of CheckoutBranch.
func (mr *MockGitWorktreeMockRecorder) CheckoutBranch(ctx, branch any) *MockGitWorktreeCheckoutBranchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckoutBranch", reflect.TypeOf((*MockGitWorktree)(nil).CheckoutBranch), ctx, branch)
	return &MockGitWorktreeCheckoutBranchCall{Call: call}
}

// MockGitWorktreeCheckoutBranchCall wrap *gomock.Call
type MockGitWorktreeCheckoutBranchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGitWorktreeCheckoutBranchCall) Return(arg0 error) *MockGitWorktreeCheckoutBranchCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGitWorktreeCheckoutBranchCall) Do(f func(context.Context, string) error) *MockGitWorktreeCheckoutBranchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGitWorktreeCheckoutBranchCall) DoAndReturn(f func(context.Context, string) error) *MockGitWorktreeCheckoutBranchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CheckoutNewBranch mocks base method.
func (m *MockGitWorktree) CheckoutNewBranch(ctx context.Context, req git.CheckoutNewBranchRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckoutNewBranch", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckoutNewBranch indicates an expected call of CheckoutNewBranch.
func (mr *MockGitWorktreeMockRecorder) CheckoutNewBranch(ctx, req any) *MockGitWorktreeCheckoutNewBranchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckoutNewBranch", reflect.TypeOf((*MockGitWorktree)(nil).CheckoutNewBranch), ctx, req)
	return &MockGitWorktreeCheckoutNewBranchCall{Call: call}
}

// MockGitWorktreeCheckoutNewBranchCall wrap *gomock.Call
type MockGitWorktreeCheckoutNewBranchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGitWorktreeCheckoutNewBranchCall) Return(arg0 error) *MockGitWorktreeCheckoutNewBranchCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGitWorktreeCheckoutNewBranchCall) Do(f func(context.Context, git.CheckoutNewBranchRequest) error) *MockGitWorktreeCheckoutNewBranchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGitWorktreeCheckoutNewBranchCall) DoAndReturn(f func(context.Context, git.CheckoutNewBranchRequest) error) *MockGitWorktreeCheckoutNewBranchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CurrentBranch mocks base method.
func (m *MockGitWorktree) CurrentBranch(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentBranch", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CurrentBranch indicates an expected call of CurrentBranch.
func (mr *MockGitWorktreeMockRecorder) CurrentBranch(ctx any) *MockGitWorktreeCurrentBranchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentBranch", reflect.TypeOf((*MockGitWorktree)(nil).CurrentBranch), ctx)
	return &MockGitWorktreeCurrentBranchCall{Call: call}
}

// MockGitWorktreeCurrentBranchCall wrap *gomock.Call
type MockGitWorktreeCurrentBranchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGitWorktreeCurrentBranchCall) Return(arg0 string, arg1 error) *MockGitWorktreeCurrentBranchCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGitWorktreeCurrentBranchCall) Do(f func(context.Context) (string, error)) *MockGitWorktreeCurrentBranchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGitWorktreeCurrentBranchCall) DoAndReturn(f func(context.Context) (string, error)) *MockGitWorktreeCurrentBranchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsClean mocks base method.
func (m *MockGitWorktree) IsClean(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsClean", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsClean indicates an expected call of IsClean.
func (mr *MockGitWorktreeMockRecorder) IsClean(ctx any) *MockGitWorktreeIsCleanCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsClean", reflect.TypeOf((*MockGitWorktree)(nil).IsClean), ctx)
	return &MockGitWorktreeIsCleanCall{Call: call}
}

// MockGitWorktreeIsCleanCall wrap *gomock.Call
type MockGitWorktreeIsCleanCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGitWorktreeIsCleanCall) Return(arg0 bool, arg1 error) *MockGitWorktreeIsCleanCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGitWorktreeIsCleanCall) Do(f func(context.Context) (bool, error)) *MockGitWorktreeIsCleanCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGitWorktreeIsCleanCall) DoAndReturn(f func(context.Context) (bool, error)) *MockGitWorktreeIsCleanCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Merge mocks base method.
func (m *MockGitWorktree) Merge(ctx context.Context, opts git.MergeOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Merge", ctx, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Merge indicates an expected call of Merge.
func (mr *MockGitWorktreeMockRecorder) Merge(ctx, opts any) *MockGitWorktreeMergeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Merge", reflect.TypeOf((*MockGitWorktree)(nil).Merge), ctx, opts)
	return &MockGitWorktreeMergeCall{Call: call}
}

// MockGitWorktreeMergeCall wrap *gomock.Call
type MockGitWorktreeMergeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGitWorktreeMergeCall) Return(arg0 error) *MockGitWorktreeMergeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGitWorktreeMergeCall) Do(f func(context.Context, git.MergeOptions) error) *MockGitWorktreeMergeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGitWorktreeMergeCall) DoAndReturn(f func(context.Context, git.MergeOptions) error) *MockGitWorktreeMergeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Push mocks base method.
func (m *MockGitWorktree) Push(ctx context.Context, opts git.PushOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Push", ctx, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Push indicates an expected call of Push.
func (mr *MockGitWorktreeMockRecorder) Push(ctx, opts any) *MockGitWorktreePushCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Push", reflect.TypeOf((*MockGitWorktree)(nil).Push), ctx, opts)
	return &MockGitWorktreePushCall{Call: call}
}

// MockGitWorktreePushCall wrap *gomock.Call
type MockGitWorktreePushCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGitWorktreePushCall) Return(arg0 error) *MockGitWorktreePushCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGitWorktreePushCall) Do(f func(context.Context, git.PushOptions) error) *MockGitWorktreePushCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGitWorktreePushCall) DoAndReturn(f func(context.Context, git.PushOptions) error) *MockGitWorktreePushCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// ClearPendingIntegrationRebuild mocks base method.
func (m *MockStore) ClearPendingIntegrationRebuild(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearPendingIntegrationRebuild", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearPendingIntegrationRebuild indicates an expected call of ClearPendingIntegrationRebuild.
func (mr *MockStoreMockRecorder) ClearPendingIntegrationRebuild(ctx any) *MockStoreClearPendingIntegrationRebuildCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearPendingIntegrationRebuild", reflect.TypeOf((*MockStore)(nil).ClearPendingIntegrationRebuild), ctx)
	return &MockStoreClearPendingIntegrationRebuildCall{Call: call}
}

// MockStoreClearPendingIntegrationRebuildCall wrap *gomock.Call
type MockStoreClearPendingIntegrationRebuildCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreClearPendingIntegrationRebuildCall) Return(arg0 error) *MockStoreClearPendingIntegrationRebuildCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreClearPendingIntegrationRebuildCall) Do(f func(context.Context) error) *MockStoreClearPendingIntegrationRebuildCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreClearPendingIntegrationRebuildCall) DoAndReturn(f func(context.Context) error) *MockStoreClearPendingIntegrationRebuildCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Integration mocks base method.
func (m *MockStore) Integration(ctx context.Context) (*state.IntegrationInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Integration", ctx)
	ret0, _ := ret[0].(*state.IntegrationInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Integration indicates an expected call of Integration.
func (mr *MockStoreMockRecorder) Integration(ctx any) *MockStoreIntegrationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Integration", reflect.TypeOf((*MockStore)(nil).Integration), ctx)
	return &MockStoreIntegrationCall{Call: call}
}

// MockStoreIntegrationCall wrap *gomock.Call
type MockStoreIntegrationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreIntegrationCall) Return(arg0 *state.IntegrationInfo, arg1 error) *MockStoreIntegrationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreIntegrationCall) Do(f func(context.Context) (*state.IntegrationInfo, error)) *MockStoreIntegrationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreIntegrationCall) DoAndReturn(f func(context.Context) (*state.IntegrationInfo, error)) *MockStoreIntegrationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PendingIntegrationRebuild mocks base method.
func (m *MockStore) PendingIntegrationRebuild(ctx context.Context) (*state.IntegrationRebuild, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PendingIntegrationRebuild", ctx)
	ret0, _ := ret[0].(*state.IntegrationRebuild)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PendingIntegrationRebuild indicates an expected call of PendingIntegrationRebuild.
func (mr *MockStoreMockRecorder) PendingIntegrationRebuild(ctx any) *MockStorePendingIntegrationRebuildCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PendingIntegrationRebuild", reflect.TypeOf((*MockStore)(nil).PendingIntegrationRebuild), ctx)
	return &MockStorePendingIntegrationRebuildCall{Call: call}
}

// MockStorePendingIntegrationRebuildCall wrap *gomock.Call
type MockStorePendingIntegrationRebuildCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStorePendingIntegrationRebuildCall) Return(arg0 *state.IntegrationRebuild, arg1 error) *MockStorePendingIntegrationRebuildCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStorePendingIntegrationRebuildCall) Do(f func(context.Context) (*state.IntegrationRebuild, error)) *MockStorePendingIntegrationRebuildCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStorePendingIntegrationRebuildCall) DoAndReturn(f func(context.Context) (*state.IntegrationRebuild, error)) *MockStorePendingIntegrationRebuildCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Remote mocks base method.
func (m *MockStore) Remote() (state.Remote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remote")
	ret0, _ := ret[0].(state.Remote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Remote indicates an expected call of Remote.
func (mr *MockStoreMockRecorder) Remote() *MockStoreRemoteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remote", reflect.TypeOf((*MockStore)(nil).Remote))
	return &MockStoreRemoteCall{Call: call}
}

// MockStoreRemoteCall wrap *gomock.Call
type MockStoreRemoteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreRemoteCall) Return(arg0 state.Remote, arg1 error) *MockStoreRemoteCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreRemoteCall) Do(f func() (state.Remote, error)) *MockStoreRemoteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreRemoteCall) DoAndReturn(f func() (state.Remote, error)) *MockStoreRemoteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetIntegration mocks base method.
func (m *MockStore) SetIntegration(ctx context.Context, info *state.IntegrationInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetIntegration", ctx, info)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetIntegration indicates an expected call of SetIntegration.
func (mr *MockStoreMockRecorder) SetIntegration(ctx, info any) *MockStoreSetIntegrationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetIntegration", reflect.TypeOf((*MockStore)(nil).SetIntegration), ctx, info)
	return &MockStoreSetIntegrationCall{Call: call}
}

// MockStoreSetIntegrationCall wrap *gomock.Call
type MockStoreSetIntegrationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreSetIntegrationCall) Return(arg0 error) *MockStoreSetIntegrationCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreSetIntegrationCall) Do(f func(context.Context, *state.IntegrationInfo) error) *MockStoreSetIntegrationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreSetIntegrationCall) DoAndReturn(f func(context.Context, *state.IntegrationInfo) error) *MockStoreSetIntegrationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetPendingIntegrationRebuild mocks base method.
func (m *MockStore) SetPendingIntegrationRebuild(ctx context.Context, rb *state.IntegrationRebuild) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPendingIntegrationRebuild", ctx, rb)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPendingIntegrationRebuild indicates an expected call of SetPendingIntegrationRebuild.
func (mr *MockStoreMockRecorder) SetPendingIntegrationRebuild(ctx, rb any) *MockStoreSetPendingIntegrationRebuildCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPendingIntegrationRebuild", reflect.TypeOf((*MockStore)(nil).SetPendingIntegrationRebuild), ctx, rb)
	return &MockStoreSetPendingIntegrationRebuildCall{Call: call}
}

// MockStoreSetPendingIntegrationRebuildCall wrap *gomock.Call
type MockStoreSetPendingIntegrationRebuildCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreSetPendingIntegrationRebuildCall) Return(arg0 error) *MockStoreSetPendingIntegrationRebuildCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreSetPendingIntegrationRebuildCall) Do(f func(context.Context, *state.IntegrationRebuild) error) *MockStoreSetPendingIntegrationRebuildCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreSetPendingIntegrationRebuildCall) DoAndReturn(f func(context.Context, *state.IntegrationRebuild) error) *MockStoreSetPendingIntegrationRebuildCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Trunk mocks base method.
func (m *MockStore) Trunk() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trunk")
	ret0, _ := ret[0].(string)
	return ret0
}

// Trunk indicates an expected call of Trunk.
func (mr *MockStoreMockRecorder) Trunk() *MockStoreTrunkCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trunk", reflect.TypeOf((*MockStore)(nil).Trunk))
	return &MockStoreTrunkCall{Call: call}
}

// MockStoreTrunkCall wrap *gomock.Call
type MockStoreTrunkCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreTrunkCall) Return(arg0 string) *MockStoreTrunkCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreTrunkCall) Do(f func() string) *MockStoreTrunkCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreTrunkCall) DoAndReturn(f func() string) *MockStoreTrunkCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// LookupBranch mocks base method.
func (m *MockService) LookupBranch(ctx context.Context, name string) (*spice.LookupBranchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupBranch", ctx, name)
	ret0, _ := ret[0].(*spice.LookupBranchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupBranch indicates an expected call of LookupBranch.
func (mr *MockServiceMockRecorder) LookupBranch(ctx, name any) *MockServiceLookupBranchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupBranch", reflect.TypeOf((*MockService)(nil).LookupBranch), ctx, name)
	return &MockServiceLookupBranchCall{Call: call}
}

// MockServiceLookupBranchCall wrap *gomock.Call
type MockServiceLookupBranchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceLookupBranchCall) Return(arg0 *spice.LookupBranchResponse, arg1 error) *MockServiceLookupBranchCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceLookupBranchCall) Do(f func(context.Context, string) (*spice.LookupBranchResponse, error)) *MockServiceLookupBranchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceLookupBranchCall) DoAndReturn(f func(context.Context, string) (*spice.LookupBranchResponse, error)) *MockServiceLookupBranchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
