// Code generated by MockGen. DO NOT EDIT.
// Source: go.abhg.dev/gs/internal/forge/azuredevops (interfaces: azureDevOpsGateway)
//
// Generated by this command:
//
//	mockgen -destination=mocks_test.go -package=azuredevops -write_package_comment=false -typed -mock_names=azureDevOpsGateway=MockAzureDevOpsGateway . azureDevOpsGateway
//

package azuredevops

import (
	context "context"
	reflect "reflect"

	azuredevops "go.abhg.dev/gs/internal/gateway/azuredevops"
	gomock "go.uber.org/mock/gomock"
)

// MockAzureDevOpsGateway is a mock of azureDevOpsGateway interface.
type MockAzureDevOpsGateway struct {
	ctrl     *gomock.Controller
	recorder *MockAzureDevOpsGatewayMockRecorder
	isgomock struct{}
}

// MockAzureDevOpsGatewayMockRecorder is the mock recorder for MockAzureDevOpsGateway.
type MockAzureDevOpsGatewayMockRecorder struct {
	mock *MockAzureDevOpsGateway
}

// NewMockAzureDevOpsGateway creates a new mock instance.
func NewMockAzureDevOpsGateway(ctrl *gomock.Controller) *MockAzureDevOpsGateway {
	mock := &MockAzureDevOpsGateway{ctrl: ctrl}
	mock.recorder = &MockAzureDevOpsGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAzureDevOpsGateway) EXPECT() *MockAzureDevOpsGatewayMockRecorder {
	return m.recorder
}

// AddComment mocks base method.
func (m *MockAzureDevOpsGateway) AddComment(arg0 context.Context, arg1, arg2 string, arg3 int, arg4 string) (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddComment", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AddComment indicates an expected call of AddComment.
func (mr *MockAzureDevOpsGatewayMockRecorder) AddComment(arg0, arg1, arg2, arg3, arg4 any) *MockAzureDevOpsGatewayAddCommentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddComment", reflect.TypeOf((*MockAzureDevOpsGateway)(nil).AddComment), arg0, arg1, arg2, arg3, arg4)
	return &MockAzureDevOpsGatewayAddCommentCall{Call: call}
}

// MockAzureDevOpsGatewayAddCommentCall wrap *gomock.Call
type MockAzureDevOpsGatewayAddCommentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAzureDevOpsGatewayAddCommentCall) Return(arg0, arg1 int, arg2 error) *MockAzureDevOpsGatewayAddCommentCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAzureDevOpsGatewayAddCommentCall) Do(f func(context.Context, string, string, int, string) (int, int, error)) *MockAzureDevOpsGatewayAddCommentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAzureDevOpsGatewayAddCommentCall) DoAndReturn(f func(context.Context, string, string, int, string) (int, int, error)) *MockAzureDevOpsGatewayAddCommentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AddLabel mocks base method.
func (m *MockAzureDevOpsGateway) AddLabel(arg0 context.Context, arg1, arg2 string, arg3 int, arg4 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLabel", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddLabel indicates an expected call of AddLabel.
func (mr *MockAzureDevOpsGatewayMockRecorder) AddLabel(arg0, arg1, arg2, arg3, arg4 any) *MockAzureDevOpsGatewayAddLabelCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLabel", reflect.TypeOf((*MockAzureDevOpsGateway)(nil).AddLabel), arg0, arg1, arg2, arg3, arg4)
	return &MockAzureDevOpsGatewayAddLabelCall{Call: call}
}

// MockAzureDevOpsGatewayAddLabelCall wrap *gomock.Call
type MockAzureDevOpsGatewayAddLabelCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAzureDevOpsGatewayAddLabelCall) Return(arg0 error) *MockAzureDevOpsGatewayAddLabelCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAzureDevOpsGatewayAddLabelCall) Do(f func(context.Context, string, string, int, string) error) *MockAzureDevOpsGatewayAddLabelCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAzureDevOpsGatewayAddLabelCall) DoAndReturn(f func(context.Context, string, string, int, string) error) *MockAzureDevOpsGatewayAddLabelCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AddReviewer mocks base method.
func (m *MockAzureDevOpsGateway) AddReviewer(arg0 context.Context, arg1, arg2 string, arg3 int, arg4 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddReviewer", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddReviewer indicates an expected call of AddReviewer.
func (mr *MockAzureDevOpsGatewayMockRecorder) AddReviewer(arg0, arg1, arg2, arg3, arg4 any) *MockAzureDevOpsGatewayAddReviewerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddReviewer", reflect.TypeOf((*MockAzureDevOpsGateway)(nil).AddReviewer), arg0, arg1, arg2, arg3, arg4)
	return &MockAzureDevOpsGatewayAddReviewerCall{Call: call}
}

// MockAzureDevOpsGatewayAddReviewerCall wrap *gomock.Call
type MockAzureDevOpsGatewayAddReviewerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAzureDevOpsGatewayAddReviewerCall) Return(arg0 error) *MockAzureDevOpsGatewayAddReviewerCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAzureDevOpsGatewayAddReviewerCall) Do(f func(context.Context, string, string, int, string) error) *MockAzureDevOpsGatewayAddReviewerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAzureDevOpsGatewayAddReviewerCall) DoAndReturn(f func(context.Context, string, string, int, string) error) *MockAzureDevOpsGatewayAddReviewerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AddReviewerByName mocks base method.
func (m *MockAzureDevOpsGateway) AddReviewerByName(arg0 context.Context, arg1, arg2 string, arg3 int, arg4 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddReviewerByName", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddReviewerByName indicates an expected call of AddReviewerByName.
func (mr *MockAzureDevOpsGatewayMockRecorder) AddReviewerByName(arg0, arg1, arg2, arg3, arg4 any) *MockAzureDevOpsGatewayAddReviewerByNameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddReviewerByName", reflect.TypeOf((*MockAzureDevOpsGateway)(nil).AddReviewerByName), arg0, arg1, arg2, arg3, arg4)
	return &MockAzureDevOpsGatewayAddReviewerByNameCall{Call: call}
}

// MockAzureDevOpsGatewayAddReviewerByNameCall wrap *gomock.Call
type MockAzureDevOpsGatewayAddReviewerByNameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAzureDevOpsGatewayAddReviewerByNameCall) Return(arg0 error) *MockAzureDevOpsGatewayAddReviewerByNameCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAzureDevOpsGatewayAddReviewerByNameCall) Do(f func(context.Context, string, string, int, string) error) *MockAzureDevOpsGatewayAddReviewerByNameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAzureDevOpsGatewayAddReviewerByNameCall) DoAndReturn(f func(context.Context, string, string, int, string) error) *MockAzureDevOpsGatewayAddReviewerByNameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CommentExists mocks base method.
func (m *MockAzureDevOpsGateway) CommentExists(arg0 context.Context, arg1, arg2 string, arg3, arg4, arg5 int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommentExists", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommentExists indicates an expected call of CommentExists.
func (mr *MockAzureDevOpsGatewayMockRecorder) CommentExists(arg0, arg1, arg2, arg3, arg4, arg5 any) *MockAzureDevOpsGatewayCommentExistsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommentExists", reflect.TypeOf((*MockAzureDevOpsGateway)(nil).CommentExists), arg0, arg1, arg2, arg3, arg4, arg5)
	return &MockAzureDevOpsGatewayCommentExistsCall{Call: call}
}

// MockAzureDevOpsGatewayCommentExistsCall wrap *gomock.Call
type MockAzureDevOpsGatewayCommentExistsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAzureDevOpsGatewayCommentExistsCall) Return(arg0 bool, arg1 error) *MockAzureDevOpsGatewayCommentExistsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAzureDevOpsGatewayCommentExistsCall) Do(f func(context.Context, string, string, int, int, int) (bool, error)) *MockAzureDevOpsGatewayCommentExistsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAzureDevOpsGatewayCommentExistsCall) DoAndReturn(f func(context.Context, string, string, int, int, int) (bool, error)) *MockAzureDevOpsGatewayCommentExistsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreatePullRequest mocks base method.
func (m *MockAzureDevOpsGateway) CreatePullRequest(arg0 context.Context, arg1 *azuredevops.CreatePullRequestInput) (*azuredevops.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePullRequest", arg0, arg1)
	ret0, _ := ret[0].(*azuredevops.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePullRequest indicates an expected call of CreatePullRequest.
func (mr *MockAzureDevOpsGatewayMockRecorder) CreatePullRequest(arg0, arg1 any) *MockAzureDevOpsGatewayCreatePullRequestCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePullRequest", reflect.TypeOf((*MockAzureDevOpsGateway)(nil).CreatePullRequest), arg0, arg1)
	return &MockAzureDevOpsGatewayCreatePullRequestCall{Call: call}
}

// MockAzureDevOpsGatewayCreatePullRequestCall wrap *gomock.Call
type MockAzureDevOpsGatewayCreatePullRequestCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAzureDevOpsGatewayCreatePullRequestCall) Return(arg0 *azuredevops.PullRequest, arg1 error) *MockAzureDevOpsGatewayCreatePullRequestCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAzureDevOpsGatewayCreatePullRequestCall) Do(f func(context.Context, *azuredevops.CreatePullRequestInput) (*azuredevops.PullRequest, error)) *MockAzureDevOpsGatewayCreatePullRequestCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAzureDevOpsGatewayCreatePullRequestCall) DoAndReturn(f func(context.Context, *azuredevops.CreatePullRequestInput) (*azuredevops.PullRequest, error)) *MockAzureDevOpsGatewayCreatePullRequestCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CurrentUserID mocks base method.
func (m *MockAzureDevOpsGateway) CurrentUserID(arg0 context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentUserID", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CurrentUserID indicates an expected call of CurrentUserID.
func (mr *MockAzureDevOpsGatewayMockRecorder) CurrentUserID(arg0 any) *MockAzureDevOpsGatewayCurrentUserIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentUserID", reflect.TypeOf((*MockAzureDevOpsGateway)(nil).CurrentUserID), arg0)
	return &MockAzureDevOpsGatewayCurrentUserIDCall{Call: call}
}

// MockAzureDevOpsGatewayCurrentUserIDCall wrap *gomock.Call
type MockAzureDevOpsGatewayCurrentUserIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAzureDevOpsGatewayCurrentUserIDCall) Return(arg0 string, arg1 error) *MockAzureDevOpsGatewayCurrentUserIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAzureDevOpsGatewayCurrentUserIDCall) Do(f func(context.Context) (string, error)) *MockAzureDevOpsGatewayCurrentUserIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAzureDevOpsGatewayCurrentUserIDCall) DoAndReturn(f func(context.Context) (string, error)) *MockAzureDevOpsGatewayCurrentUserIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteComment mocks base method.
func (m *MockAzureDevOpsGateway) DeleteComment(arg0 context.Context, arg1, arg2 string, arg3, arg4, arg5 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteComment", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteComment indicates an expected call of DeleteComment.
func (mr *MockAzureDevOpsGatewayMockRecorder) DeleteComment(arg0, arg1, arg2, arg3, arg4, arg5 any) *MockAzureDevOpsGatewayDeleteCommentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteComment", reflect.TypeOf((*MockAzureDevOpsGateway)(nil).DeleteComment), arg0, arg1, arg2, arg3, arg4, arg5)
	return &MockAzureDevOpsGatewayDeleteCommentCall{Call: call}
}

// MockAzureDevOpsGatewayDeleteCommentCall wrap *gomock.Call
type MockAzureDevOpsGatewayDeleteCommentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAzureDevOpsGatewayDeleteCommentCall) Return(arg0 error) *MockAzureDevOpsGatewayDeleteCommentCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAzureDevOpsGatewayDeleteCommentCall) Do(f func(context.Context, string, string, int, int, int) error) *MockAzureDevOpsGatewayDeleteCommentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAzureDevOpsGatewayDeleteCommentCall) DoAndReturn(f func(context.Context, string, string, int, int, int) error) *MockAzureDevOpsGatewayDeleteCommentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindPullRequests mocks base method.
func (m *MockAzureDevOpsGateway) FindPullRequests(arg0 context.Context, arg1 *azuredevops.FindPullRequestsInput) ([]*azuredevops.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPullRequests", arg0, arg1)
	ret0, _ := ret[0].([]*azuredevops.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPullRequests indicates an expected call of FindPullRequests.
func (mr *MockAzureDevOpsGatewayMockRecorder) FindPullRequests(arg0, arg1 any) *MockAzureDevOpsGatewayFindPullRequestsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPullRequests", reflect.TypeOf((*MockAzureDevOpsGateway)(nil).FindPullRequests), arg0, arg1)
	return &MockAzureDevOpsGatewayFindPullRequestsCall{Call: call}
}

// MockAzureDevOpsGatewayFindPullRequestsCall wrap *gomock.Call
type MockAzureDevOpsGatewayFindPullRequestsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAzureDevOpsGatewayFindPullRequestsCall) Return(arg0 []*azuredevops.PullRequest, arg1 error) *MockAzureDevOpsGatewayFindPullRequestsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAzureDevOpsGatewayFindPullRequestsCall) Do(f func(context.Context, *azuredevops.FindPullRequestsInput) ([]*azuredevops.PullRequest, error)) *MockAzureDevOpsGatewayFindPullRequestsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAzureDevOpsGatewayFindPullRequestsCall) DoAndReturn(f func(context.Context, *azuredevops.FindPullRequestsInput) ([]*azuredevops.PullRequest, error)) *MockAzureDevOpsGatewayFindPullRequestsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Item mocks base method.
func (m *MockAzureDevOpsGateway) Item(arg0 context.Context, arg1, arg2, arg3 string) (*azuredevops.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Item", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*azuredevops.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Item indicates an expected call of Item.
func (mr *MockAzureDevOpsGatewayMockRecorder) Item(arg0, arg1, arg2, arg3 any) *MockAzureDevOpsGatewayItemCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Item", reflect.TypeOf((*MockAzureDevOpsGateway)(nil).Item), arg0, arg1, arg2, arg3)
	return &MockAzureDevOpsGatewayItemCall{Call: call}
}

// MockAzureDevOpsGatewayItemCall wrap *gomock.Call
type MockAzureDevOpsGatewayItemCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAzureDevOpsGatewayItemCall) Return(arg0 *azuredevops.Item, arg1 error) *MockAzureDevOpsGatewayItemCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAzureDevOpsGatewayItemCall) Do(f func(context.Context, string, string, string) (*azuredevops.Item, error)) *MockAzureDevOpsGatewayItemCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAzureDevOpsGatewayItemCall) DoAndReturn(f func(context.Context, string, string, string) (*azuredevops.Item, error)) *MockAzureDevOpsGatewayItemCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Items mocks base method.
func (m *MockAzureDevOpsGateway) Items(arg0 context.Context, arg1, arg2, arg3 string) ([]azuredevops.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Items", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]azuredevops.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Items indicates an expected call of Items.
func (mr *MockAzureDevOpsGatewayMockRecorder) Items(arg0, arg1, arg2, arg3 any) *MockAzureDevOpsGatewayItemsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Items", reflect.TypeOf((*MockAzureDevOpsGateway)(nil).Items), arg0, arg1, arg2, arg3)
	return &MockAzureDevOpsGatewayItemsCall{Call: call}
}

// MockAzureDevOpsGatewayItemsCall wrap *gomock.Call
type MockAzureDevOpsGatewayItemsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAzureDevOpsGatewayItemsCall) Return(arg0 []azuredevops.Item, arg1 error) *MockAzureDevOpsGatewayItemsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAzureDevOpsGatewayItemsCall) Do(f func(context.Context, string, string, string) ([]azuredevops.Item, error)) *MockAzureDevOpsGatewayItemsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAzureDevOpsGatewayItemsCall) DoAndReturn(f func(context.Context, string, string, string) ([]azuredevops.Item, error)) *MockAzureDevOpsGatewayItemsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Labels mocks base method.
func (m *MockAzureDevOpsGateway) Labels(arg0 context.Context, arg1, arg2 string, arg3 int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Labels", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Labels indicates an expected call of Labels.
func (mr *MockAzureDevOpsGatewayMockRecorder) Labels(arg0, arg1, arg2, arg3 any) *MockAzureDevOpsGatewayLabelsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Labels", reflect.TypeOf((*MockAzureDevOpsGateway)(nil).Labels), arg0, arg1, arg2, arg3)
	return &MockAzureDevOpsGatewayLabelsCall{Call: call}
}

// MockAzureDevOpsGatewayLabelsCall wrap *gomock.Call
type MockAzureDevOpsGatewayLabelsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAzureDevOpsGatewayLabelsCall) Return(arg0 []string, arg1 error) *MockAzureDevOpsGatewayLabelsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAzureDevOpsGatewayLabelsCall) Do(f func(context.Context, string, string, int) ([]string, error)) *MockAzureDevOpsGatewayLabelsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAzureDevOpsGatewayLabelsCall) DoAndReturn(f func(context.Context, string, string, int) ([]string, error)) *MockAzureDevOpsGatewayLabelsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PullRequest mocks base method.
func (m *MockAzureDevOpsGateway) PullRequest(arg0 context.Context, arg1, arg2 string, arg3 int) (*azuredevops.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PullRequest", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*azuredevops.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PullRequest indicates an expected call of PullRequest.
func (mr *MockAzureDevOpsGatewayMockRecorder) PullRequest(arg0, arg1, arg2, arg3 any) *MockAzureDevOpsGatewayPullRequestCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullRequest", reflect.TypeOf((*MockAzureDevOpsGateway)(nil).PullRequest), arg0, arg1, arg2, arg3)
	return &MockAzureDevOpsGatewayPullRequestCall{Call: call}
}

// MockAzureDevOpsGatewayPullRequestCall wrap *gomock.Call
type MockAzureDevOpsGatewayPullRequestCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAzureDevOpsGatewayPullRequestCall) Return(arg0 *azuredevops.PullRequest, arg1 error) *MockAzureDevOpsGatewayPullRequestCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAzureDevOpsGatewayPullRequestCall) Do(f func(context.Context, string, string, int) (*azuredevops.PullRequest, error)) *MockAzureDevOpsGatewayPullRequestCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAzureDevOpsGatewayPullRequestCall) DoAndReturn(f func(context.Context, string, string, int) (*azuredevops.PullRequest, error)) *MockAzureDevOpsGatewayPullRequestCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RefExists mocks base method.
func (m *MockAzureDevOpsGateway) RefExists(arg0 context.Context, arg1, arg2, arg3 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefExists", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefExists indicates an expected call of RefExists.
func (mr *MockAzureDevOpsGatewayMockRecorder) RefExists(arg0, arg1, arg2, arg3 any) *MockAzureDevOpsGatewayRefExistsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefExists", reflect.TypeOf((*MockAzureDevOpsGateway)(nil).RefExists), arg0, arg1, arg2, arg3)
	return &MockAzureDevOpsGatewayRefExistsCall{Call: call}
}

// MockAzureDevOpsGatewayRefExistsCall wrap *gomock.Call
type MockAzureDevOpsGatewayRefExistsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAzureDevOpsGatewayRefExistsCall) Return(arg0 bool, arg1 error) *MockAzureDevOpsGatewayRefExistsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAzureDevOpsGatewayRefExistsCall) Do(f func(context.Context, string, string, string) (bool, error)) *MockAzureDevOpsGatewayRefExistsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAzureDevOpsGatewayRefExistsCall) DoAndReturn(f func(context.Context, string, string, string) (bool, error)) *MockAzureDevOpsGatewayRefExistsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Repository mocks base method.
func (m *MockAzureDevOpsGateway) Repository(arg0 context.Context, arg1, arg2 string) (*azuredevops.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Repository", arg0, arg1, arg2)
	ret0, _ := ret[0].(*azuredevops.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Repository indicates an expected call of Repository.
func (mr *MockAzureDevOpsGatewayMockRecorder) Repository(arg0, arg1, arg2 any) *MockAzureDevOpsGatewayRepositoryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Repository", reflect.TypeOf((*MockAzureDevOpsGateway)(nil).Repository), arg0, arg1, arg2)
	return &MockAzureDevOpsGatewayRepositoryCall{Call: call}
}

// MockAzureDevOpsGatewayRepositoryCall wrap *gomock.Call
type MockAzureDevOpsGatewayRepositoryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAzureDevOpsGatewayRepositoryCall) Return(arg0 *azuredevops.Repository, arg1 error) *MockAzureDevOpsGatewayRepositoryCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAzureDevOpsGatewayRepositoryCall) Do(f func(context.Context, string, string) (*azuredevops.Repository, error)) *MockAzureDevOpsGatewayRepositoryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAzureDevOpsGatewayRepositoryCall) DoAndReturn(f func(context.Context, string, string) (*azuredevops.Repository, error)) *MockAzureDevOpsGatewayRepositoryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ReviewerID mocks base method.
func (m *MockAzureDevOpsGateway) ReviewerID(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReviewerID", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReviewerID indicates an expected call of ReviewerID.
func (mr *MockAzureDevOpsGatewayMockRecorder) ReviewerID(arg0, arg1 any) *MockAzureDevOpsGatewayReviewerIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReviewerID", reflect.TypeOf((*MockAzureDevOpsGateway)(nil).ReviewerID), arg0, arg1)
	return &MockAzureDevOpsGatewayReviewerIDCall{Call: call}
}

// MockAzureDevOpsGatewayReviewerIDCall wrap *gomock.Call
type MockAzureDevOpsGatewayReviewerIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAzureDevOpsGatewayReviewerIDCall) Return(arg0 string, arg1 error) *MockAzureDevOpsGatewayReviewerIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAzureDevOpsGatewayReviewerIDCall) Do(f func(context.Context, string) (string, error)) *MockAzureDevOpsGatewayReviewerIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAzureDevOpsGatewayReviewerIDCall) DoAndReturn(f func(context.Context, string) (string, error)) *MockAzureDevOpsGatewayReviewerIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Reviewers mocks base method.
func (m *MockAzureDevOpsGateway) Reviewers(arg0 context.Context, arg1, arg2 string, arg3 int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reviewers", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reviewers indicates an expected call of Reviewers.
func (mr *MockAzureDevOpsGatewayMockRecorder) Reviewers(arg0, arg1, arg2, arg3 any) *MockAzureDevOpsGatewayReviewersCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reviewers", reflect.TypeOf((*MockAzureDevOpsGateway)(nil).Reviewers), arg0, arg1, arg2, arg3)
	return &MockAzureDevOpsGatewayReviewersCall{Call: call}
}

// MockAzureDevOpsGatewayReviewersCall wrap *gomock.Call
type MockAzureDevOpsGatewayReviewersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAzureDevOpsGatewayReviewersCall) Return(arg0 []string, arg1 error) *MockAzureDevOpsGatewayReviewersCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAzureDevOpsGatewayReviewersCall) Do(f func(context.Context, string, string, int) ([]string, error)) *MockAzureDevOpsGatewayReviewersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAzureDevOpsGatewayReviewersCall) DoAndReturn(f func(context.Context, string, string, int) ([]string, error)) *MockAzureDevOpsGatewayReviewersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Threads mocks base method.
func (m *MockAzureDevOpsGateway) Threads(arg0 context.Context, arg1, arg2 string, arg3 int) ([]azuredevops.Thread, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Threads", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]azuredevops.Thread)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Threads indicates an expected call of Threads.
func (mr *MockAzureDevOpsGatewayMockRecorder) Threads(arg0, arg1, arg2, arg3 any) *MockAzureDevOpsGatewayThreadsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Threads", reflect.TypeOf((*MockAzureDevOpsGateway)(nil).Threads), arg0, arg1, arg2, arg3)
	return &MockAzureDevOpsGatewayThreadsCall{Call: call}
}

// MockAzureDevOpsGatewayThreadsCall wrap *gomock.Call
type MockAzureDevOpsGatewayThreadsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAzureDevOpsGatewayThreadsCall) Return(arg0 []azuredevops.Thread, arg1 error) *MockAzureDevOpsGatewayThreadsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAzureDevOpsGatewayThreadsCall) Do(f func(context.Context, string, string, int) ([]azuredevops.Thread, error)) *MockAzureDevOpsGatewayThreadsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAzureDevOpsGatewayThreadsCall) DoAndReturn(f func(context.Context, string, string, int) ([]azuredevops.Thread, error)) *MockAzureDevOpsGatewayThreadsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateComment mocks base method.
func (m *MockAzureDevOpsGateway) UpdateComment(arg0 context.Context, arg1, arg2 string, arg3, arg4, arg5 int, arg6 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateComment", arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateComment indicates an expected call of UpdateComment.
func (mr *MockAzureDevOpsGatewayMockRecorder) UpdateComment(arg0, arg1, arg2, arg3, arg4, arg5, arg6 any) *MockAzureDevOpsGatewayUpdateCommentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateComment", reflect.TypeOf((*MockAzureDevOpsGateway)(nil).UpdateComment), arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	return &MockAzureDevOpsGatewayUpdateCommentCall{Call: call}
}

// MockAzureDevOpsGatewayUpdateCommentCall wrap *gomock.Call
type MockAzureDevOpsGatewayUpdateCommentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAzureDevOpsGatewayUpdateCommentCall) Return(arg0 error) *MockAzureDevOpsGatewayUpdateCommentCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAzureDevOpsGatewayUpdateCommentCall) Do(f func(context.Context, string, string, int, int, int, string) error) *MockAzureDevOpsGatewayUpdateCommentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAzureDevOpsGatewayUpdateCommentCall) DoAndReturn(f func(context.Context, string, string, int, int, int, string) error) *MockAzureDevOpsGatewayUpdateCommentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdatePullRequest mocks base method.
func (m *MockAzureDevOpsGateway) UpdatePullRequest(arg0 context.Context, arg1 *azuredevops.UpdatePullRequestInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePullRequest", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePullRequest indicates an expected call of UpdatePullRequest.
func (mr *MockAzureDevOpsGatewayMockRecorder) UpdatePullRequest(arg0, arg1 any) *MockAzureDevOpsGatewayUpdatePullRequestCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePullRequest", reflect.TypeOf((*MockAzureDevOpsGateway)(nil).UpdatePullRequest), arg0, arg1)
	return &MockAzureDevOpsGatewayUpdatePullRequestCall{Call: call}
}

// MockAzureDevOpsGatewayUpdatePullRequestCall wrap *gomock.Call
type MockAzureDevOpsGatewayUpdatePullRequestCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAzureDevOpsGatewayUpdatePullRequestCall) Return(arg0 error) *MockAzureDevOpsGatewayUpdatePullRequestCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAzureDevOpsGatewayUpdatePullRequestCall) Do(f func(context.Context, *azuredevops.UpdatePullRequestInput) error) *MockAzureDevOpsGatewayUpdatePullRequestCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAzureDevOpsGatewayUpdatePullRequestCall) DoAndReturn(f func(context.Context, *azuredevops.UpdatePullRequestInput) error) *MockAzureDevOpsGatewayUpdatePullRequestCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
