// Code generated by MockGen. DO NOT EDIT.
// Source: go.abhg.dev/gs/internal/forge/github (interfaces: githubGateway)
//
// Generated by this command:
//
//	mockgen -destination=mocks_test.go -package=github -write_package_comment=false -typed -mock_names=githubGateway=MockGithubGateway . githubGateway
//

package github

import (
	context "context"
	iter "iter"
	reflect "reflect"

	github "go.abhg.dev/gs/internal/gateway/github"
	gomock "go.uber.org/mock/gomock"
)

// MockGithubGateway is a mock of githubGateway interface.
type MockGithubGateway struct {
	ctrl     *gomock.Controller
	recorder *MockGithubGatewayMockRecorder
	isgomock struct{}
}

// MockGithubGatewayMockRecorder is the mock recorder for MockGithubGateway.
type MockGithubGatewayMockRecorder struct {
	mock *MockGithubGateway
}

// NewMockGithubGateway creates a new mock instance.
func NewMockGithubGateway(ctrl *gomock.Controller) *MockGithubGateway {
	mock := &MockGithubGateway{ctrl: ctrl}
	mock.recorder = &MockGithubGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGithubGateway) EXPECT() *MockGithubGatewayMockRecorder {
	return m.recorder
}

// AddComment mocks base method.
func (m *MockGithubGateway) AddComment(arg0 context.Context, arg1 github.ID, arg2 string) (*github.AddedComment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddComment", arg0, arg1, arg2)
	ret0, _ := ret[0].(*github.AddedComment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddComment indicates an expected call of AddComment.
func (mr *MockGithubGatewayMockRecorder) AddComment(arg0, arg1, arg2 any) *MockGithubGatewayAddCommentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddComment", reflect.TypeOf((*MockGithubGateway)(nil).AddComment), arg0, arg1, arg2)
	return &MockGithubGatewayAddCommentCall{Call: call}
}

// MockGithubGatewayAddCommentCall wrap *gomock.Call
type MockGithubGatewayAddCommentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGithubGatewayAddCommentCall) Return(arg0 *github.AddedComment, arg1 error) *MockGithubGatewayAddCommentCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGithubGatewayAddCommentCall) Do(f func(context.Context, github.ID, string) (*github.AddedComment, error)) *MockGithubGatewayAddCommentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGithubGatewayAddCommentCall) DoAndReturn(f func(context.Context, github.ID, string) (*github.AddedComment, error)) *MockGithubGatewayAddCommentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AddPullRequestMetadata mocks base method.
func (m *MockGithubGateway) AddPullRequestMetadata(arg0 context.Context, arg1 *github.PullRequestMetadataInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPullRequestMetadata", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPullRequestMetadata indicates an expected call of AddPullRequestMetadata.
func (mr *MockGithubGatewayMockRecorder) AddPullRequestMetadata(arg0, arg1 any) *MockGithubGatewayAddPullRequestMetadataCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPullRequestMetadata", reflect.TypeOf((*MockGithubGateway)(nil).AddPullRequestMetadata), arg0, arg1)
	return &MockGithubGatewayAddPullRequestMetadataCall{Call: call}
}

// MockGithubGatewayAddPullRequestMetadataCall wrap *gomock.Call
type MockGithubGatewayAddPullRequestMetadataCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGithubGatewayAddPullRequestMetadataCall) Return(arg0 error) *MockGithubGatewayAddPullRequestMetadataCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGithubGatewayAddPullRequestMetadataCall) Do(f func(context.Context, *github.PullRequestMetadataInput) error) *MockGithubGatewayAddPullRequestMetadataCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGithubGatewayAddPullRequestMetadataCall) DoAndReturn(f func(context.Context, *github.PullRequestMetadataInput) error) *MockGithubGatewayAddPullRequestMetadataCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AddPullRequestReview mocks base method.
func (m *MockGithubGateway) AddPullRequestReview(arg0 context.Context, arg1 *github.AddPullRequestReviewInput) (*github.AddedPullRequestReview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPullRequestReview", arg0, arg1)
	ret0, _ := ret[0].(*github.AddedPullRequestReview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPullRequestReview indicates an expected call of AddPullRequestReview.
func (mr *MockGithubGatewayMockRecorder) AddPullRequestReview(arg0, arg1 any) *MockGithubGatewayAddPullRequestReviewCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPullRequestReview", reflect.TypeOf((*MockGithubGateway)(nil).AddPullRequestReview), arg0, arg1)
	return &MockGithubGatewayAddPullRequestReviewCall{Call: call}
}

// MockGithubGatewayAddPullRequestReviewCall wrap *gomock.Call
type MockGithubGatewayAddPullRequestReviewCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGithubGatewayAddPullRequestReviewCall) Return(arg0 *github.AddedPullRequestReview, arg1 error) *MockGithubGatewayAddPullRequestReviewCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGithubGatewayAddPullRequestReviewCall) Do(f func(context.Context, *github.AddPullRequestReviewInput) (*github.AddedPullRequestReview, error)) *MockGithubGatewayAddPullRequestReviewCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGithubGatewayAddPullRequestReviewCall) DoAndReturn(f func(context.Context, *github.AddPullRequestReviewInput) (*github.AddedPullRequestReview, error)) *MockGithubGatewayAddPullRequestReviewCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AddPullRequestReviewThread mocks base method.
func (m *MockGithubGateway) AddPullRequestReviewThread(arg0 context.Context, arg1 *github.AddPullRequestReviewThreadInput) (*github.AddedPullRequestReviewThread, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPullRequestReviewThread", arg0, arg1)
	ret0, _ := ret[0].(*github.AddedPullRequestReviewThread)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPullRequestReviewThread indicates an expected call of AddPullRequestReviewThread.
func (mr *MockGithubGatewayMockRecorder) AddPullRequestReviewThread(arg0, arg1 any) *MockGithubGatewayAddPullRequestReviewThreadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPullRequestReviewThread", reflect.TypeOf((*MockGithubGateway)(nil).AddPullRequestReviewThread), arg0, arg1)
	return &MockGithubGatewayAddPullRequestReviewThreadCall{Call: call}
}

// MockGithubGatewayAddPullRequestReviewThreadCall wrap *gomock.Call
type MockGithubGatewayAddPullRequestReviewThreadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGithubGatewayAddPullRequestReviewThreadCall) Return(arg0 *github.AddedPullRequestReviewThread, arg1 error) *MockGithubGatewayAddPullRequestReviewThreadCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGithubGatewayAddPullRequestReviewThreadCall) Do(f func(context.Context, *github.AddPullRequestReviewThreadInput) (*github.AddedPullRequestReviewThread, error)) *MockGithubGatewayAddPullRequestReviewThreadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGithubGatewayAddPullRequestReviewThreadCall) DoAndReturn(f func(context.Context, *github.AddPullRequestReviewThreadInput) (*github.AddedPullRequestReviewThread, error)) *MockGithubGatewayAddPullRequestReviewThreadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AddPullRequestReviewThreadReply mocks base method.
func (m *MockGithubGateway) AddPullRequestReviewThreadReply(arg0 context.Context, arg1 *github.AddPullRequestReviewThreadReplyInput) (*github.AddedPullRequestReviewComment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPullRequestReviewThreadReply", arg0, arg1)
	ret0, _ := ret[0].(*github.AddedPullRequestReviewComment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPullRequestReviewThreadReply indicates an expected call of AddPullRequestReviewThreadReply.
func (mr *MockGithubGatewayMockRecorder) AddPullRequestReviewThreadReply(arg0, arg1 any) *MockGithubGatewayAddPullRequestReviewThreadReplyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPullRequestReviewThreadReply", reflect.TypeOf((*MockGithubGateway)(nil).AddPullRequestReviewThreadReply), arg0, arg1)
	return &MockGithubGatewayAddPullRequestReviewThreadReplyCall{Call: call}
}

// MockGithubGatewayAddPullRequestReviewThreadReplyCall wrap *gomock.Call
type MockGithubGatewayAddPullRequestReviewThreadReplyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGithubGatewayAddPullRequestReviewThreadReplyCall) Return(arg0 *github.AddedPullRequestReviewComment, arg1 error) *MockGithubGatewayAddPullRequestReviewThreadReplyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGithubGatewayAddPullRequestReviewThreadReplyCall) Do(f func(context.Context, *github.AddPullRequestReviewThreadReplyInput) (*github.AddedPullRequestReviewComment, error)) *MockGithubGatewayAddPullRequestReviewThreadReplyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGithubGatewayAddPullRequestReviewThreadReplyCall) DoAndReturn(f func(context.Context, *github.AddPullRequestReviewThreadReplyInput) (*github.AddedPullRequestReviewComment, error)) *MockGithubGatewayAddPullRequestReviewThreadReplyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ChangeStatuses mocks base method.
func (m *MockGithubGateway) ChangeStatuses(arg0 context.Context, arg1 []github.ID) ([]*github.ChangeStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeStatuses", arg0, arg1)
	ret0, _ := ret[0].([]*github.ChangeStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangeStatuses indicates an expected call of ChangeStatuses.
func (mr *MockGithubGatewayMockRecorder) ChangeStatuses(arg0, arg1 any) *MockGithubGatewayChangeStatusesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeStatuses", reflect.TypeOf((*MockGithubGateway)(nil).ChangeStatuses), arg0, arg1)
	return &MockGithubGatewayChangeStatusesCall{Call: call}
}

// MockGithubGatewayChangeStatusesCall wrap *gomock.Call
type MockGithubGatewayChangeStatusesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGithubGatewayChangeStatusesCall) Return(arg0 []*github.ChangeStatus, arg1 error) *MockGithubGatewayChangeStatusesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGithubGatewayChangeStatusesCall) Do(f func(context.Context, []github.ID) ([]*github.ChangeStatus, error)) *MockGithubGatewayChangeStatusesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGithubGatewayChangeStatusesCall) DoAndReturn(f func(context.Context, []github.ID) ([]*github.ChangeStatus, error)) *MockGithubGatewayChangeStatusesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ChangeTemplates mocks base method.
func (m *MockGithubGateway) ChangeTemplates(arg0 context.Context, arg1, arg2 string) ([]*github.ChangeTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeTemplates", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*github.ChangeTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangeTemplates indicates an expected call of ChangeTemplates.
func (mr *MockGithubGatewayMockRecorder) ChangeTemplates(arg0, arg1, arg2 any) *MockGithubGatewayChangeTemplatesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeTemplates", reflect.TypeOf((*MockGithubGateway)(nil).ChangeTemplates), arg0, arg1, arg2)
	return &MockGithubGatewayChangeTemplatesCall{Call: call}
}

// MockGithubGatewayChangeTemplatesCall wrap *gomock.Call
type MockGithubGatewayChangeTemplatesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGithubGatewayChangeTemplatesCall) Return(arg0 []*github.ChangeTemplate, arg1 error) *MockGithubGatewayChangeTemplatesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGithubGatewayChangeTemplatesCall) Do(f func(context.Context, string, string) ([]*github.ChangeTemplate, error)) *MockGithubGatewayChangeTemplatesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGithubGatewayChangeTemplatesCall) DoAndReturn(f func(context.Context, string, string) ([]*github.ChangeTemplate, error)) *MockGithubGatewayChangeTemplatesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ClosePullRequest mocks base method.
func (m *MockGithubGateway) ClosePullRequest(arg0 context.Context, arg1 github.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClosePullRequest", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClosePullRequest indicates an expected call of ClosePullRequest.
func (mr *MockGithubGatewayMockRecorder) ClosePullRequest(arg0, arg1 any) *MockGithubGatewayClosePullRequestCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClosePullRequest", reflect.TypeOf((*MockGithubGateway)(nil).ClosePullRequest), arg0, arg1)
	return &MockGithubGatewayClosePullRequestCall{Call: call}
}

// MockGithubGatewayClosePullRequestCall wrap *gomock.Call
type MockGithubGatewayClosePullRequestCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGithubGatewayClosePullRequestCall) Return(arg0 error) *MockGithubGatewayClosePullRequestCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGithubGatewayClosePullRequestCall) Do(f func(context.Context, github.ID) error) *MockGithubGatewayClosePullRequestCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGithubGatewayClosePullRequestCall) DoAndReturn(f func(context.Context, github.ID) error) *MockGithubGatewayClosePullRequestCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ConvertPullRequestToDraft mocks base method.
func (m *MockGithubGateway) ConvertPullRequestToDraft(arg0 context.Context, arg1 github.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConvertPullRequestToDraft", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConvertPullRequestToDraft indicates an expected call of ConvertPullRequestToDraft.
func (mr *MockGithubGatewayMockRecorder) ConvertPullRequestToDraft(arg0, arg1 any) *MockGithubGatewayConvertPullRequestToDraftCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConvertPullRequestToDraft", reflect.TypeOf((*MockGithubGateway)(nil).ConvertPullRequestToDraft), arg0, arg1)
	return &MockGithubGatewayConvertPullRequestToDraftCall{Call: call}
}

// MockGithubGatewayConvertPullRequestToDraftCall wrap *gomock.Call
type MockGithubGatewayConvertPullRequestToDraftCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGithubGatewayConvertPullRequestToDraftCall) Return(arg0 error) *MockGithubGatewayConvertPullRequestToDraftCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGithubGatewayConvertPullRequestToDraftCall) Do(f func(context.Context, github.ID) error) *MockGithubGatewayConvertPullRequestToDraftCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGithubGatewayConvertPullRequestToDraftCall) DoAndReturn(f func(context.Context, github.ID) error) *MockGithubGatewayConvertPullRequestToDraftCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateLabel mocks base method.
func (m *MockGithubGateway) CreateLabel(arg0 context.Context, arg1 github.ID, arg2, arg3 string) (github.ID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLabel", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(github.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLabel indicates an expected call of CreateLabel.
func (mr *MockGithubGatewayMockRecorder) CreateLabel(arg0, arg1, arg2, arg3 any) *MockGithubGatewayCreateLabelCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLabel", reflect.TypeOf((*MockGithubGateway)(nil).CreateLabel), arg0, arg1, arg2, arg3)
	return &MockGithubGatewayCreateLabelCall{Call: call}
}

// MockGithubGatewayCreateLabelCall wrap *gomock.Call
type MockGithubGatewayCreateLabelCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGithubGatewayCreateLabelCall) Return(arg0 github.ID, arg1 error) *MockGithubGatewayCreateLabelCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGithubGatewayCreateLabelCall) Do(f func(context.Context, github.ID, string, string) (github.ID, error)) *MockGithubGatewayCreateLabelCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGithubGatewayCreateLabelCall) DoAndReturn(f func(context.Context, github.ID, string, string) (github.ID, error)) *MockGithubGatewayCreateLabelCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreatePullRequest mocks base method.
func (m *MockGithubGateway) CreatePullRequest(arg0 context.Context, arg1 *github.CreatePullRequestInput) (*github.CreatedPullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePullRequest", arg0, arg1)
	ret0, _ := ret[0].(*github.CreatedPullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePullRequest indicates an expected call of CreatePullRequest.
func (mr *MockGithubGatewayMockRecorder) CreatePullRequest(arg0, arg1 any) *MockGithubGatewayCreatePullRequestCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePullRequest", reflect.TypeOf((*MockGithubGateway)(nil).CreatePullRequest), arg0, arg1)
	return &MockGithubGatewayCreatePullRequestCall{Call: call}
}

// MockGithubGatewayCreatePullRequestCall wrap *gomock.Call
type MockGithubGatewayCreatePullRequestCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGithubGatewayCreatePullRequestCall) Return(arg0 *github.CreatedPullRequest, arg1 error) *MockGithubGatewayCreatePullRequestCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGithubGatewayCreatePullRequestCall) Do(f func(context.Context, *github.CreatePullRequestInput) (*github.CreatedPullRequest, error)) *MockGithubGatewayCreatePullRequestCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGithubGatewayCreatePullRequestCall) DoAndReturn(f func(context.Context, *github.CreatePullRequestInput) (*github.CreatedPullRequest, error)) *MockGithubGatewayCreatePullRequestCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteIssueComment mocks base method.
func (m *MockGithubGateway) DeleteIssueComment(arg0 context.Context, arg1 github.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIssueComment", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIssueComment indicates an expected call of DeleteIssueComment.
func (mr *MockGithubGatewayMockRecorder) DeleteIssueComment(arg0, arg1 any) *MockGithubGatewayDeleteIssueCommentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIssueComment", reflect.TypeOf((*MockGithubGateway)(nil).DeleteIssueComment), arg0, arg1)
	return &MockGithubGatewayDeleteIssueCommentCall{Call: call}
}

// MockGithubGatewayDeleteIssueCommentCall wrap *gomock.Call
type MockGithubGatewayDeleteIssueCommentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGithubGatewayDeleteIssueCommentCall) Return(arg0 error) *MockGithubGatewayDeleteIssueCommentCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGithubGatewayDeleteIssueCommentCall) Do(f func(context.Context, github.ID) error) *MockGithubGatewayDeleteIssueCommentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGithubGatewayDeleteIssueCommentCall) DoAndReturn(f func(context.Context, github.ID) error) *MockGithubGatewayDeleteIssueCommentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteLabel mocks base method.
func (m *MockGithubGateway) DeleteLabel(arg0 context.Context, arg1 github.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLabel", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLabel indicates an expected call of DeleteLabel.
func (mr *MockGithubGatewayMockRecorder) DeleteLabel(arg0, arg1 any) *MockGithubGatewayDeleteLabelCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLabel", reflect.TypeOf((*MockGithubGateway)(nil).DeleteLabel), arg0, arg1)
	return &MockGithubGatewayDeleteLabelCall{Call: call}
}

// MockGithubGatewayDeleteLabelCall wrap *gomock.Call
type MockGithubGatewayDeleteLabelCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGithubGatewayDeleteLabelCall) Return(arg0 error) *MockGithubGatewayDeleteLabelCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGithubGatewayDeleteLabelCall) Do(f func(context.Context, github.ID) error) *MockGithubGatewayDeleteLabelCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGithubGatewayDeleteLabelCall) DoAndReturn(f func(context.Context, github.ID) error) *MockGithubGatewayDeleteLabelCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindPullRequests mocks base method.
func (m *MockGithubGateway) FindPullRequests(arg0 context.Context, arg1, arg2, arg3 string, arg4 int, arg5 []github.PullRequestState) ([]*github.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPullRequests", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].([]*github.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPullRequests indicates an expected call of FindPullRequests.
func (mr *MockGithubGatewayMockRecorder) FindPullRequests(arg0, arg1, arg2, arg3, arg4, arg5 any) *MockGithubGatewayFindPullRequestsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPullRequests", reflect.TypeOf((*MockGithubGateway)(nil).FindPullRequests), arg0, arg1, arg2, arg3, arg4, arg5)
	return &MockGithubGatewayFindPullRequestsCall{Call: call}
}

// MockGithubGatewayFindPullRequestsCall wrap *gomock.Call
type MockGithubGatewayFindPullRequestsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGithubGatewayFindPullRequestsCall) Return(arg0 []*github.PullRequest, arg1 error) *MockGithubGatewayFindPullRequestsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGithubGatewayFindPullRequestsCall) Do(f func(context.Context, string, string, string, int, []github.PullRequestState) ([]*github.PullRequest, error)) *MockGithubGatewayFindPullRequestsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGithubGatewayFindPullRequestsCall) DoAndReturn(f func(context.Context, string, string, string, int, []github.PullRequestState) ([]*github.PullRequest, error)) *MockGithubGatewayFindPullRequestsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindPullRequestsByBranches mocks base method.
func (m *MockGithubGateway) FindPullRequestsByBranches(arg0 context.Context, arg1 *github.FindPullRequestsByBranchesRequest) ([][]*github.PullRequestBranchMatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPullRequestsByBranches", arg0, arg1)
	ret0, _ := ret[0].([][]*github.PullRequestBranchMatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPullRequestsByBranches indicates an expected call of FindPullRequestsByBranches.
func (mr *MockGithubGatewayMockRecorder) FindPullRequestsByBranches(arg0, arg1 any) *MockGithubGatewayFindPullRequestsByBranchesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPullRequestsByBranches", reflect.TypeOf((*MockGithubGateway)(nil).FindPullRequestsByBranches), arg0, arg1)
	return &MockGithubGatewayFindPullRequestsByBranchesCall{Call: call}
}

// MockGithubGatewayFindPullRequestsByBranchesCall wrap *gomock.Call
type MockGithubGatewayFindPullRequestsByBranchesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGithubGatewayFindPullRequestsByBranchesCall) Return(arg0 [][]*github.PullRequestBranchMatch, arg1 error) *MockGithubGatewayFindPullRequestsByBranchesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGithubGatewayFindPullRequestsByBranchesCall) Do(f func(context.Context, *github.FindPullRequestsByBranchesRequest) ([][]*github.PullRequestBranchMatch, error)) *MockGithubGatewayFindPullRequestsByBranchesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGithubGatewayFindPullRequestsByBranchesCall) DoAndReturn(f func(context.Context, *github.FindPullRequestsByBranchesRequest) ([][]*github.PullRequestBranchMatch, error)) *MockGithubGatewayFindPullRequestsByBranchesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IdentityIDs mocks base method.
func (m *MockGithubGateway) IdentityIDs(arg0 context.Context, arg1 []string, arg2 []github.TeamName) ([]github.ID, []github.ID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IdentityIDs", arg0, arg1, arg2)
	ret0, _ := ret[0].([]github.ID)
	ret1, _ := ret[1].([]github.ID)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// IdentityIDs indicates an expected call of IdentityIDs.
func (mr *MockGithubGatewayMockRecorder) IdentityIDs(arg0, arg1, arg2 any) *MockGithubGatewayIdentityIDsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IdentityIDs", reflect.TypeOf((*MockGithubGateway)(nil).IdentityIDs), arg0, arg1, arg2)
	return &MockGithubGatewayIdentityIDsCall{Call: call}
}

// MockGithubGatewayIdentityIDsCall wrap *gomock.Call
type MockGithubGatewayIdentityIDsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGithubGatewayIdentityIDsCall) Return(arg0, arg1 []github.ID, arg2 error) *MockGithubGatewayIdentityIDsCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGithubGatewayIdentityIDsCall) Do(f func(context.Context, []string, []github.TeamName) ([]github.ID, []github.ID, error)) *MockGithubGatewayIdentityIDsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGithubGatewayIdentityIDsCall) DoAndReturn(f func(context.Context, []string, []github.TeamName) ([]github.ID, []github.ID, error)) *MockGithubGatewayIdentityIDsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LabelIDs mocks base method.
func (m *MockGithubGateway) LabelIDs(arg0 context.Context, arg1, arg2 string, arg3 []string) ([]github.ID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LabelIDs", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]github.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LabelIDs indicates an expected call of LabelIDs.
func (mr *MockGithubGatewayMockRecorder) LabelIDs(arg0, arg1, arg2, arg3 any) *MockGithubGatewayLabelIDsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LabelIDs", reflect.TypeOf((*MockGithubGateway)(nil).LabelIDs), arg0, arg1, arg2, arg3)
	return &MockGithubGatewayLabelIDsCall{Call: call}
}

// MockGithubGatewayLabelIDsCall wrap *gomock.Call
type MockGithubGatewayLabelIDsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGithubGatewayLabelIDsCall) Return(arg0 []github.ID, arg1 error) *MockGithubGatewayLabelIDsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGithubGatewayLabelIDsCall) Do(f func(context.Context, string, string, []string) ([]github.ID, error)) *MockGithubGatewayLabelIDsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGithubGatewayLabelIDsCall) DoAndReturn(f func(context.Context, string, string, []string) ([]github.ID, error)) *MockGithubGatewayLabelIDsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MarkPullRequestReadyForReview mocks base method.
func (m *MockGithubGateway) MarkPullRequestReadyForReview(arg0 context.Context, arg1 github.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPullRequestReadyForReview", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkPullRequestReadyForReview indicates an expected call of MarkPullRequestReadyForReview.
func (mr *MockGithubGatewayMockRecorder) MarkPullRequestReadyForReview(arg0, arg1 any) *MockGithubGatewayMarkPullRequestReadyForReviewCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPullRequestReadyForReview", reflect.TypeOf((*MockGithubGateway)(nil).MarkPullRequestReadyForReview), arg0, arg1)
	return &MockGithubGatewayMarkPullRequestReadyForReviewCall{Call: call}
}

// MockGithubGatewayMarkPullRequestReadyForReviewCall wrap *gomock.Call
type MockGithubGatewayMarkPullRequestReadyForReviewCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGithubGatewayMarkPullRequestReadyForReviewCall) Return(arg0 error) *MockGithubGatewayMarkPullRequestReadyForReviewCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGithubGatewayMarkPullRequestReadyForReviewCall) Do(f func(context.Context, github.ID) error) *MockGithubGatewayMarkPullRequestReadyForReviewCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGithubGatewayMarkPullRequestReadyForReviewCall) DoAndReturn(f func(context.Context, github.ID) error) *MockGithubGatewayMarkPullRequestReadyForReviewCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MergePullRequest mocks base method.
func (m *MockGithubGateway) MergePullRequest(arg0 context.Context, arg1 *github.MergePullRequestInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergePullRequest", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// MergePullRequest indicates an expected call of MergePullRequest.
func (mr *MockGithubGatewayMockRecorder) MergePullRequest(arg0, arg1 any) *MockGithubGatewayMergePullRequestCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergePullRequest", reflect.TypeOf((*MockGithubGateway)(nil).MergePullRequest), arg0, arg1)
	return &MockGithubGatewayMergePullRequestCall{Call: call}
}

// MockGithubGatewayMergePullRequestCall wrap *gomock.Call
type MockGithubGatewayMergePullRequestCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGithubGatewayMergePullRequestCall) Return(arg0 error) *MockGithubGatewayMergePullRequestCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGithubGatewayMergePullRequestCall) Do(f func(context.Context, *github.MergePullRequestInput) error) *MockGithubGatewayMergePullRequestCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGithubGatewayMergePullRequestCall) DoAndReturn(f func(context.Context, *github.MergePullRequestInput) error) *MockGithubGatewayMergePullRequestCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PullRequest mocks base method.
func (m *MockGithubGateway) PullRequest(arg0 context.Context, arg1, arg2 string, arg3 int) (*github.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PullRequest", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*github.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PullRequest indicates an expected call of PullRequest.
func (mr *MockGithubGatewayMockRecorder) PullRequest(arg0, arg1, arg2, arg3 any) *MockGithubGatewayPullRequestCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullRequest", reflect.TypeOf((*MockGithubGateway)(nil).PullRequest), arg0, arg1, arg2, arg3)
	return &MockGithubGatewayPullRequestCall{Call: call}
}

// MockGithubGatewayPullRequestCall wrap *gomock.Call
type MockGithubGatewayPullRequestCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGithubGatewayPullRequestCall) Return(arg0 *github.PullRequest, arg1 error) *MockGithubGatewayPullRequestCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGithubGatewayPullRequestCall) Do(f func(context.Context, string, string, int) (*github.PullRequest, error)) *MockGithubGatewayPullRequestCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGithubGatewayPullRequestCall) DoAndReturn(f func(context.Context, string, string, int) (*github.PullRequest, error)) *MockGithubGatewayPullRequestCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PullRequestComments mocks base method.
func (m *MockGithubGateway) PullRequestComments(arg0 context.Context, arg1 github.ID, arg2 *github.PaginationOptions) iter.Seq2[*github.Comment, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PullRequestComments", arg0, arg1, arg2)
	ret0, _ := ret[0].(iter.Seq2[*github.Comment, error])
	return ret0
}

// PullRequestComments indicates an expected call of PullRequestComments.
func (mr *MockGithubGatewayMockRecorder) PullRequestComments(arg0, arg1, arg2 any) *MockGithubGatewayPullRequestCommentsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullRequestComments", reflect.TypeOf((*MockGithubGateway)(nil).PullRequestComments), arg0, arg1, arg2)
	return &MockGithubGatewayPullRequestCommentsCall{Call: call}
}

// MockGithubGatewayPullRequestCommentsCall wrap *gomock.Call
type MockGithubGatewayPullRequestCommentsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGithubGatewayPullRequestCommentsCall) Return(arg0 iter.Seq2[*github.Comment, error]) *MockGithubGatewayPullRequestCommentsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGithubGatewayPullRequestCommentsCall) Do(f func(context.Context, github.ID, *github.PaginationOptions) iter.Seq2[*github.Comment, error]) *MockGithubGatewayPullRequestCommentsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGithubGatewayPullRequestCommentsCall) DoAndReturn(f func(context.Context, github.ID, *github.PaginationOptions) iter.Seq2[*github.Comment, error]) *MockGithubGatewayPullRequestCommentsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PullRequestID mocks base method.
func (m *MockGithubGateway) PullRequestID(arg0 context.Context, arg1, arg2 string, arg3 int) (github.ID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PullRequestID", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(github.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PullRequestID indicates an expected call of PullRequestID.
func (mr *MockGithubGatewayMockRecorder) PullRequestID(arg0, arg1, arg2, arg3 any) *MockGithubGatewayPullRequestIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullRequestID", reflect.TypeOf((*MockGithubGateway)(nil).PullRequestID), arg0, arg1, arg2, arg3)
	return &MockGithubGatewayPullRequestIDCall{Call: call}
}

// MockGithubGatewayPullRequestIDCall wrap *gomock.Call
type MockGithubGatewayPullRequestIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGithubGatewayPullRequestIDCall) Return(arg0 github.ID, arg1 error) *MockGithubGatewayPullRequestIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGithubGatewayPullRequestIDCall) Do(f func(context.Context, string, string, int) (github.ID, error)) *MockGithubGatewayPullRequestIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGithubGatewayPullRequestIDCall) DoAndReturn(f func(context.Context, string, string, int) (github.ID, error)) *MockGithubGatewayPullRequestIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PullRequestLatestOpinionatedReviews mocks base method.
func (m *MockGithubGateway) PullRequestLatestOpinionatedReviews(arg0 context.Context, arg1 github.ID, arg2 *github.PaginationOptions) iter.Seq2[*github.PullRequestLatestOpinionatedReview, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PullRequestLatestOpinionatedReviews", arg0, arg1, arg2)
	ret0, _ := ret[0].(iter.Seq2[*github.PullRequestLatestOpinionatedReview, error])
	return ret0
}

// PullRequestLatestOpinionatedReviews indicates an expected call of PullRequestLatestOpinionatedReviews.
func (mr *MockGithubGatewayMockRecorder) PullRequestLatestOpinionatedReviews(arg0, arg1, arg2 any) *MockGithubGatewayPullRequestLatestOpinionatedReviewsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullRequestLatestOpinionatedReviews", reflect.TypeOf((*MockGithubGateway)(nil).PullRequestLatestOpinionatedReviews), arg0, arg1, arg2)
	return &MockGithubGatewayPullRequestLatestOpinionatedReviewsCall{Call: call}
}

// MockGithubGatewayPullRequestLatestOpinionatedReviewsCall wrap *gomock.Call
type MockGithubGatewayPullRequestLatestOpinionatedReviewsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGithubGatewayPullRequestLatestOpinionatedReviewsCall) Return(arg0 iter.Seq2[*github.PullRequestLatestOpinionatedReview, error]) *MockGithubGatewayPullRequestLatestOpinionatedReviewsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGithubGatewayPullRequestLatestOpinionatedReviewsCall) Do(f func(context.Context, github.ID, *github.PaginationOptions) iter.Seq2[*github.PullRequestLatestOpinionatedReview, error]) *MockGithubGatewayPullRequestLatestOpinionatedReviewsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGithubGatewayPullRequestLatestOpinionatedReviewsCall) DoAndReturn(f func(context.Context, github.ID, *github.PaginationOptions) iter.Seq2[*github.PullRequestLatestOpinionatedReview, error]) *MockGithubGatewayPullRequestLatestOpinionatedReviewsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PullRequestMergeability mocks base method.
func (m *MockGithubGateway) PullRequestMergeability(arg0 context.Context, arg1 github.ID) (*github.Mergeability, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PullRequestMergeability", arg0, arg1)
	ret0, _ := ret[0].(*github.Mergeability)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PullRequestMergeability indicates an expected call of PullRequestMergeability.
func (mr *MockGithubGatewayMockRecorder) PullRequestMergeability(arg0, arg1 any) *MockGithubGatewayPullRequestMergeabilityCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullRequestMergeability", reflect.TypeOf((*MockGithubGateway)(nil).PullRequestMergeability), arg0, arg1)
	return &MockGithubGatewayPullRequestMergeabilityCall{Call: call}
}

// MockGithubGatewayPullRequestMergeabilityCall wrap *gomock.Call
type MockGithubGatewayPullRequestMergeabilityCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGithubGatewayPullRequestMergeabilityCall) Return(arg0 *github.Mergeability, arg1 error) *MockGithubGatewayPullRequestMergeabilityCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGithubGatewayPullRequestMergeabilityCall) Do(f func(context.Context, github.ID) (*github.Mergeability, error)) *MockGithubGatewayPullRequestMergeabilityCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGithubGatewayPullRequestMergeabilityCall) DoAndReturn(f func(context.Context, github.ID) (*github.Mergeability, error)) *MockGithubGatewayPullRequestMergeabilityCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PullRequestReviewThreadCounts mocks base method.
func (m *MockGithubGateway) PullRequestReviewThreadCounts(arg0 context.Context, arg1 []github.ID, arg2 *github.PaginationOptions) ([]*github.ReviewThreadCounts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PullRequestReviewThreadCounts", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*github.ReviewThreadCounts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PullRequestReviewThreadCounts indicates an expected call of PullRequestReviewThreadCounts.
func (mr *MockGithubGatewayMockRecorder) PullRequestReviewThreadCounts(arg0, arg1, arg2 any) *MockGithubGatewayPullRequestReviewThreadCountsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullRequestReviewThreadCounts", reflect.TypeOf((*MockGithubGateway)(nil).PullRequestReviewThreadCounts), arg0, arg1, arg2)
	return &MockGithubGatewayPullRequestReviewThreadCountsCall{Call: call}
}

// MockGithubGatewayPullRequestReviewThreadCountsCall wrap *gomock.Call
type MockGithubGatewayPullRequestReviewThreadCountsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGithubGatewayPullRequestReviewThreadCountsCall) Return(arg0 []*github.ReviewThreadCounts, arg1 error) *MockGithubGatewayPullRequestReviewThreadCountsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGithubGatewayPullRequestReviewThreadCountsCall) Do(f func(context.Context, []github.ID, *github.PaginationOptions) ([]*github.ReviewThreadCounts, error)) *MockGithubGatewayPullRequestReviewThreadCountsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGithubGatewayPullRequestReviewThreadCountsCall) DoAndReturn(f func(context.Context, []github.ID, *github.PaginationOptions) ([]*github.ReviewThreadCounts, error)) *MockGithubGatewayPullRequestReviewThreadCountsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PullRequestReviewThreads mocks base method.
func (m *MockGithubGateway) PullRequestReviewThreads(arg0 context.Context, arg1 github.ID, arg2 *github.PaginationOptions) iter.Seq2[*github.PullRequestReviewThread, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PullRequestReviewThreads", arg0, arg1, arg2)
	ret0, _ := ret[0].(iter.Seq2[*github.PullRequestReviewThread, error])
	return ret0
}

// PullRequestReviewThreads indicates an expected call of PullRequestReviewThreads.
func (mr *MockGithubGatewayMockRecorder) PullRequestReviewThreads(arg0, arg1, arg2 any) *MockGithubGatewayPullRequestReviewThreadsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullRequestReviewThreads", reflect.TypeOf((*MockGithubGateway)(nil).PullRequestReviewThreads), arg0, arg1, arg2)
	return &MockGithubGatewayPullRequestReviewThreadsCall{Call: call}
}

// MockGithubGatewayPullRequestReviewThreadsCall wrap *gomock.Call
type MockGithubGatewayPullRequestReviewThreadsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGithubGatewayPullRequestReviewThreadsCall) Return(arg0 iter.Seq2[*github.PullRequestReviewThread, error]) *MockGithubGatewayPullRequestReviewThreadsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGithubGatewayPullRequestReviewThreadsCall) Do(f func(context.Context, github.ID, *github.PaginationOptions) iter.Seq2[*github.PullRequestReviewThread, error]) *MockGithubGatewayPullRequestReviewThreadsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGithubGatewayPullRequestReviewThreadsCall) DoAndReturn(f func(context.Context, github.ID, *github.PaginationOptions) iter.Seq2[*github.PullRequestReviewThread, error]) *MockGithubGatewayPullRequestReviewThreadsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RefExists mocks base method.
func (m *MockGithubGateway) RefExists(arg0 context.Context, arg1, arg2, arg3 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefExists", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefExists indicates an expected call of RefExists.
func (mr *MockGithubGatewayMockRecorder) RefExists(arg0, arg1, arg2, arg3 any) *MockGithubGatewayRefExistsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefExists", reflect.TypeOf((*MockGithubGateway)(nil).RefExists), arg0, arg1, arg2, arg3)
	return &MockGithubGatewayRefExistsCall{Call: call}
}

// MockGithubGatewayRefExistsCall wrap *gomock.Call
type MockGithubGatewayRefExistsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGithubGatewayRefExistsCall) Return(arg0 bool, arg1 error) *MockGithubGatewayRefExistsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGithubGatewayRefExistsCall) Do(f func(context.Context, string, string, string) (bool, error)) *MockGithubGatewayRefExistsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGithubGatewayRefExistsCall) DoAndReturn(f func(context.Context, string, string, string) (bool, error)) *MockGithubGatewayRefExistsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RepositoryID mocks base method.
func (m *MockGithubGateway) RepositoryID(arg0 context.Context, arg1, arg2 string) (github.ID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RepositoryID", arg0, arg1, arg2)
	ret0, _ := ret[0].(github.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RepositoryID indicates an expected call of RepositoryID.
func (mr *MockGithubGatewayMockRecorder) RepositoryID(arg0, arg1, arg2 any) *MockGithubGatewayRepositoryIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RepositoryID", reflect.TypeOf((*MockGithubGateway)(nil).RepositoryID), arg0, arg1, arg2)
	return &MockGithubGatewayRepositoryIDCall{Call: call}
}

// MockGithubGatewayRepositoryIDCall wrap *gomock.Call
type MockGithubGatewayRepositoryIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGithubGatewayRepositoryIDCall) Return(arg0 github.ID, arg1 error) *MockGithubGatewayRepositoryIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGithubGatewayRepositoryIDCall) Do(f func(context.Context, string, string) (github.ID, error)) *MockGithubGatewayRepositoryIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGithubGatewayRepositoryIDCall) DoAndReturn(f func(context.Context, string, string) (github.ID, error)) *MockGithubGatewayRepositoryIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ResolveReviewThread mocks base method.
func (m *MockGithubGateway) ResolveReviewThread(arg0 context.Context, arg1 github.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveReviewThread", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResolveReviewThread indicates an expected call of ResolveReviewThread.
func (mr *MockGithubGatewayMockRecorder) ResolveReviewThread(arg0, arg1 any) *MockGithubGatewayResolveReviewThreadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveReviewThread", reflect.TypeOf((*MockGithubGateway)(nil).ResolveReviewThread), arg0, arg1)
	return &MockGithubGatewayResolveReviewThreadCall{Call: call}
}

// MockGithubGatewayResolveReviewThreadCall wrap *gomock.Call
type MockGithubGatewayResolveReviewThreadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGithubGatewayResolveReviewThreadCall) Return(arg0 error) *MockGithubGatewayResolveReviewThreadCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGithubGatewayResolveReviewThreadCall) Do(f func(context.Context, github.ID) error) *MockGithubGatewayResolveReviewThreadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGithubGatewayResolveReviewThreadCall) DoAndReturn(f func(context.Context, github.ID) error) *MockGithubGatewayResolveReviewThreadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// StatusChecks mocks base method.
func (m *MockGithubGateway) StatusChecks(arg0 context.Context, arg1 github.ID, arg2 *github.PaginationOptions) iter.Seq2[github.StatusCheck, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatusChecks", arg0, arg1, arg2)
	ret0, _ := ret[0].(iter.Seq2[github.StatusCheck, error])
	return ret0
}

// StatusChecks indicates an expected call of StatusChecks.
func (mr *MockGithubGatewayMockRecorder) StatusChecks(arg0, arg1, arg2 any) *MockGithubGatewayStatusChecksCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatusChecks", reflect.TypeOf((*MockGithubGateway)(nil).StatusChecks), arg0, arg1, arg2)
	return &MockGithubGatewayStatusChecksCall{Call: call}
}

// MockGithubGatewayStatusChecksCall wrap *gomock.Call
type MockGithubGatewayStatusChecksCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGithubGatewayStatusChecksCall) Return(arg0 iter.Seq2[github.StatusCheck, error]) *MockGithubGatewayStatusChecksCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGithubGatewayStatusChecksCall) Do(f func(context.Context, github.ID, *github.PaginationOptions) iter.Seq2[github.StatusCheck, error]) *MockGithubGatewayStatusChecksCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGithubGatewayStatusChecksCall) DoAndReturn(f func(context.Context, github.ID, *github.PaginationOptions) iter.Seq2[github.StatusCheck, error]) *MockGithubGatewayStatusChecksCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SubmitPullRequestReview mocks base method.
func (m *MockGithubGateway) SubmitPullRequestReview(arg0 context.Context, arg1 *github.SubmitPullRequestReviewInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitPullRequestReview", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubmitPullRequestReview indicates an expected call of SubmitPullRequestReview.
func (mr *MockGithubGatewayMockRecorder) SubmitPullRequestReview(arg0, arg1 any) *MockGithubGatewaySubmitPullRequestReviewCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitPullRequestReview", reflect.TypeOf((*MockGithubGateway)(nil).SubmitPullRequestReview), arg0, arg1)
	return &MockGithubGatewaySubmitPullRequestReviewCall{Call: call}
}

// MockGithubGatewaySubmitPullRequestReviewCall wrap *gomock.Call
type MockGithubGatewaySubmitPullRequestReviewCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGithubGatewaySubmitPullRequestReviewCall) Return(arg0 error) *MockGithubGatewaySubmitPullRequestReviewCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGithubGatewaySubmitPullRequestReviewCall) Do(f func(context.Context, *github.SubmitPullRequestReviewInput) error) *MockGithubGatewaySubmitPullRequestReviewCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGithubGatewaySubmitPullRequestReviewCall) DoAndReturn(f func(context.Context, *github.SubmitPullRequestReviewInput) error) *MockGithubGatewaySubmitPullRequestReviewCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UnresolveReviewThread mocks base method.
func (m *MockGithubGateway) UnresolveReviewThread(arg0 context.Context, arg1 github.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnresolveReviewThread", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnresolveReviewThread indicates an expected call of UnresolveReviewThread.
func (mr *MockGithubGatewayMockRecorder) UnresolveReviewThread(arg0, arg1 any) *MockGithubGatewayUnresolveReviewThreadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnresolveReviewThread", reflect.TypeOf((*MockGithubGateway)(nil).UnresolveReviewThread), arg0, arg1)
	return &MockGithubGatewayUnresolveReviewThreadCall{Call: call}
}

// MockGithubGatewayUnresolveReviewThreadCall wrap *gomock.Call
type MockGithubGatewayUnresolveReviewThreadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGithubGatewayUnresolveReviewThreadCall) Return(arg0 error) *MockGithubGatewayUnresolveReviewThreadCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGithubGatewayUnresolveReviewThreadCall) Do(f func(context.Context, github.ID) error) *MockGithubGatewayUnresolveReviewThreadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGithubGatewayUnresolveReviewThreadCall) DoAndReturn(f func(context.Context, github.ID) error) *MockGithubGatewayUnresolveReviewThreadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateIssueComment mocks base method.
func (m *MockGithubGateway) UpdateIssueComment(arg0 context.Context, arg1 github.ID, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIssueComment", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateIssueComment indicates an expected call of UpdateIssueComment.
func (mr *MockGithubGatewayMockRecorder) UpdateIssueComment(arg0, arg1, arg2 any) *MockGithubGatewayUpdateIssueCommentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIssueComment", reflect.TypeOf((*MockGithubGateway)(nil).UpdateIssueComment), arg0, arg1, arg2)
	return &MockGithubGatewayUpdateIssueCommentCall{Call: call}
}

// MockGithubGatewayUpdateIssueCommentCall wrap *gomock.Call
type MockGithubGatewayUpdateIssueCommentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGithubGatewayUpdateIssueCommentCall) Return(arg0 error) *MockGithubGatewayUpdateIssueCommentCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGithubGatewayUpdateIssueCommentCall) Do(f func(context.Context, github.ID, string) error) *MockGithubGatewayUpdateIssueCommentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGithubGatewayUpdateIssueCommentCall) DoAndReturn(f func(context.Context, github.ID, string) error) *MockGithubGatewayUpdateIssueCommentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdatePullRequest mocks base method.
func (m *MockGithubGateway) UpdatePullRequest(arg0 context.Context, arg1 *github.UpdatePullRequestInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePullRequest", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePullRequest indicates an expected call of UpdatePullRequest.
func (mr *MockGithubGatewayMockRecorder) UpdatePullRequest(arg0, arg1 any) *MockGithubGatewayUpdatePullRequestCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePullRequest", reflect.TypeOf((*MockGithubGateway)(nil).UpdatePullRequest), arg0, arg1)
	return &MockGithubGatewayUpdatePullRequestCall{Call: call}
}

// MockGithubGatewayUpdatePullRequestCall wrap *gomock.Call
type MockGithubGatewayUpdatePullRequestCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGithubGatewayUpdatePullRequestCall) Return(arg0 error) *MockGithubGatewayUpdatePullRequestCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGithubGatewayUpdatePullRequestCall) Do(f func(context.Context, *github.UpdatePullRequestInput) error) *MockGithubGatewayUpdatePullRequestCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGithubGatewayUpdatePullRequestCall) DoAndReturn(f func(context.Context, *github.UpdatePullRequestInput) error) *MockGithubGatewayUpdatePullRequestCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdatePullRequestReviewComment mocks base method.
func (m *MockGithubGateway) UpdatePullRequestReviewComment(arg0 context.Context, arg1 github.ID, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePullRequestReviewComment", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePullRequestReviewComment indicates an expected call of UpdatePullRequestReviewComment.
func (mr *MockGithubGatewayMockRecorder) UpdatePullRequestReviewComment(arg0, arg1, arg2 any) *MockGithubGatewayUpdatePullRequestReviewCommentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePullRequestReviewComment", reflect.TypeOf((*MockGithubGateway)(nil).UpdatePullRequestReviewComment), arg0, arg1, arg2)
	return &MockGithubGatewayUpdatePullRequestReviewCommentCall{Call: call}
}

// MockGithubGatewayUpdatePullRequestReviewCommentCall wrap *gomock.Call
type MockGithubGatewayUpdatePullRequestReviewCommentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGithubGatewayUpdatePullRequestReviewCommentCall) Return(arg0 error) *MockGithubGatewayUpdatePullRequestReviewCommentCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGithubGatewayUpdatePullRequestReviewCommentCall) Do(f func(context.Context, github.ID, string) error) *MockGithubGatewayUpdatePullRequestReviewCommentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGithubGatewayUpdatePullRequestReviewCommentCall) DoAndReturn(f func(context.Context, github.ID, string) error) *MockGithubGatewayUpdatePullRequestReviewCommentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
