// Code generated by MockGen. DO NOT EDIT.
// Source: go.abhg.dev/gs/internal/handler/continuation (interfaces: GitWorktree,Store,CommandParser,Command)
//
// Generated by this command:
//
//	mockgen -package continuation -destination mocks_test.go . GitWorktree,Store,CommandParser,Command
//

// Package continuation is a generated GoMock package.
package continuation

import (
	context "context"
	reflect "reflect"

	git "go.abhg.dev/gs/internal/git"
	state "go.abhg.dev/gs/internal/spice/state"
	gomock "go.uber.org/mock/gomock"
)

// MockGitWorktree is a mock of GitWorktree interface.
type MockGitWorktree struct {
	ctrl     *gomock.Controller
	recorder *MockGitWorktreeMockRecorder
	isgomock struct{}
}

// MockGitWorktreeMockRecorder is the mock recorder for MockGitWorktree.
type MockGitWorktreeMockRecorder struct {
	mock *MockGitWorktree
}

// NewMockGitWorktree creates a new mock instance.
func NewMockGitWorktree(ctrl *gomock.Controller) *MockGitWorktree {
	mock := &MockGitWorktree{ctrl: ctrl}
	mock.recorder = &MockGitWorktreeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitWorktree) EXPECT() *MockGitWorktreeMockRecorder {
	return m.recorder
}

// CheckoutBranch mocks base method.
func (m *MockGitWorktree) CheckoutBranch(ctx context.Context, branch string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckoutBranch", ctx, branch)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckoutBranch indicates an expected call of CheckoutBranch.
func (mr *MockGitWorktreeMockRecorder) CheckoutBranch(ctx, branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckoutBranch", reflect.TypeOf((*MockGitWorktree)(nil).CheckoutBranch), ctx, branch)
}

// MergeAbort mocks base method.
func (m *MockGitWorktree) MergeAbort(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergeAbort", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// MergeAbort indicates an expected call of MergeAbort.
func (mr *MockGitWorktreeMockRecorder) MergeAbort(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergeAbort", reflect.TypeOf((*MockGitWorktree)(nil).MergeAbort), ctx)
}

// MergeContinue mocks base method.
func (m *MockGitWorktree) MergeContinue(ctx context.Context, opts *git.MergeContinueOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergeContinue", ctx, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// MergeContinue indicates an expected call of MergeContinue.
func (mr *MockGitWorktreeMockRecorder) MergeContinue(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergeContinue", reflect.TypeOf((*MockGitWorktree)(nil).MergeContinue), ctx, opts)
}

// MergeState mocks base method.
func (m *MockGitWorktree) MergeState(ctx context.Context) (*git.MergeState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergeState", ctx)
	ret0, _ := ret[0].(*git.MergeState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MergeState indicates an expected call of MergeState.
func (mr *MockGitWorktreeMockRecorder) MergeState(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergeState", reflect.TypeOf((*MockGitWorktree)(nil).MergeState), ctx)
}

// RebaseAbort mocks base method.
func (m *MockGitWorktree) RebaseAbort(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RebaseAbort", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RebaseAbort indicates an expected call of RebaseAbort.
func (mr *MockGitWorktreeMockRecorder) RebaseAbort(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RebaseAbort", reflect.TypeOf((*MockGitWorktree)(nil).RebaseAbort), ctx)
}

// RebaseContinue mocks base method.
func (m *MockGitWorktree) RebaseContinue(ctx context.Context, opts *git.RebaseContinueOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RebaseContinue", ctx, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// RebaseContinue indicates an expected call of RebaseContinue.
func (mr *MockGitWorktreeMockRecorder) RebaseContinue(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RebaseContinue", reflect.TypeOf((*MockGitWorktree)(nil).RebaseContinue), ctx, opts)
}

// RebaseState mocks base method.
func (m *MockGitWorktree) RebaseState(ctx context.Context) (*git.RebaseState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RebaseState", ctx)
	ret0, _ := ret[0].(*git.RebaseState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RebaseState indicates an expected call of RebaseState.
func (mr *MockGitWorktreeMockRecorder) RebaseState(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RebaseState", reflect.TypeOf((*MockGitWorktree)(nil).RebaseState), ctx)
}

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AppendContinuations mocks base method.
func (m *MockStore) AppendContinuations(ctx context.Context, msg string, conts ...state.Continuation) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, msg}
	for _, a := range conts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AppendContinuations", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendContinuations indicates an expected call of AppendContinuations.
func (mr *MockStoreMockRecorder) AppendContinuations(ctx, msg any, conts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, msg}, conts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendContinuations", reflect.TypeOf((*MockStore)(nil).AppendContinuations), varargs...)
}

// TakeContinuations mocks base method.
func (m *MockStore) TakeContinuations(ctx context.Context, msg string) ([]state.Continuation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TakeContinuations", ctx, msg)
	ret0, _ := ret[0].([]state.Continuation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TakeContinuations indicates an expected call of TakeContinuations.
func (mr *MockStoreMockRecorder) TakeContinuations(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TakeContinuations", reflect.TypeOf((*MockStore)(nil).TakeContinuations), ctx, msg)
}

// MockCommandParser is a mock of CommandParser interface.
type MockCommandParser struct {
	ctrl     *gomock.Controller
	recorder *MockCommandParserMockRecorder
	isgomock struct{}
}

// MockCommandParserMockRecorder is the mock recorder for MockCommandParser.
type MockCommandParserMockRecorder struct {
	mock *MockCommandParser
}

// NewMockCommandParser creates a new mock instance.
func NewMockCommandParser(ctrl *gomock.Controller) *MockCommandParser {
	mock := &MockCommandParser{ctrl: ctrl}
	mock.recorder = &MockCommandParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandParser) EXPECT() *MockCommandParserMockRecorder {
	return m.recorder
}

// Parse mocks base method.
func (m *MockCommandParser) Parse(args []string) (Command, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", args)
	ret0, _ := ret[0].(Command)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MockCommandParserMockRecorder) Parse(args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockCommandParser)(nil).Parse), args)
}

// MockCommand is a mock of Command interface.
type MockCommand struct {
	ctrl     *gomock.Controller
	recorder *MockCommandMockRecorder
	isgomock struct{}
}

// MockCommandMockRecorder is the mock recorder for MockCommand.
type MockCommandMockRecorder struct {
	mock *MockCommand
}

// NewMockCommand creates a new mock instance.
func NewMockCommand(ctrl *gomock.Controller) *MockCommand {
	mock := &MockCommand{ctrl: ctrl}
	mock.recorder = &MockCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommand) EXPECT() *MockCommandMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockCommand) Run(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockCommandMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockCommand)(nil).Run), ctx)
}
