name: Update merged changelog

# When a .changes/v*.md file is modified in a release PR,
# we should update the root CHANGELOG.md.

on:
  pull_request:
    branches: [ 'main' ]

jobs:
  merge:
    name: Merge
    runs-on: ubuntu-latest

    # Run only if the PR is a release PR.
    if: >-
      contains(
        github.event.pull_request.labels.*.name,
        'prepare-release'
      )

    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        token: ${{ secrets.PAT }}  # for push

    - uses: jdx/mise-action@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - run: changie merge

    - name: Push changes
      uses: stefanzweifel/git-auto-commit-action@v6
      with:
        commit_message: Update CHANGELOG.md
        file_pattern: CHANGELOG.md
