name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GO_VERSION: 1.23.x
  GOLANGCI_LINT_VERSION: v1.60.1

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Check out repository
    - uses: actions/setup-go@v5
      name: Set up Go
      with:
        go-version: ${{ env.GO_VERSION }}
    - uses: golangci/golangci-lint-action@v6
      name: Install golangci-lint
      with:
        version: ${{ env.GOLANGCI_LINT_VERSION }}
        args: --help
    - run: make lint
      name: Lint

  test:
    runs-on: ${{ matrix.os }}
    name: Test (${{ matrix.os}})
    strategy:
      matrix:
        os: ["ubuntu-latest"] # TODO: ["windows-latest"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Test
      run: make cover
      shell: bash

    - name: Upload coverage
      uses: codecov/codecov-action@v4.5.0
      with:
        files: ./cover.out
        token: ${{ secrets.CODECOV_TOKEN }}

  # Depends on lint and test.
  # Stable name for branch protection to require
  # instead of adding lint and test there directly.
  ok:
    name: OK
    runs-on: ubuntu-latest
    needs: [lint, test]

    # Workaround for GitHub marking this job as skipped,
    # and allowing a bad PR to merge anyway.
    if: always()
    steps:
    - run: exit 1
      if: >-
        needs.lint.result != 'success' ||
        needs.test.result != 'success'

    - run: exit 0
