name: Prepare release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release (e.g. v1.2.3)
        required: false
        default: 'auto'
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-pr:
    runs-on: ubuntu-latest
    name: Generate release PR

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: jdx/mise-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - id: run
      run: |
        changie batch ${{ inputs.version }}
        changie merge
        echo "latest=$(changie latest)" >> "$GITHUB_OUTPUT"

    - name: Update unreleased references in docs
      run: |
        grep -rlF '<!-- gs:version unreleased -->' doc/src |
          xargs perl -p -i -e \
          's/<!-- gs:version unreleased -->/<!-- gs:version ${{ steps.run.outputs.latest }} -->/g'


    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        title: Release ${{ steps.run.outputs.latest }}
        branch: release/${{ steps.run.outputs.latest }}
        labels: prepare-release
        commit-message: Release ${{ steps.run.outputs.latest }}
        token: ${{ secrets.PAT }}
        body: ''
