name: Prepare release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release (e.g. v1.2.3)
        required: false
        default: 'auto'
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-pr:
    runs-on: ubuntu-latest
    name: Generate release PR

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: jdx/mise-action@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - id: run
      run: |
        mise run release:prepare ${{ inputs.version }}
        mise run generate

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        title: Release ${{ steps.run.outputs.latest }}
        branch: release/${{ steps.run.outputs.latest }}
        labels: prepare-release
        commit-message: Release ${{ steps.run.outputs.latest }}
        token: ${{ secrets.PAT }}
        body: ''
